### ISSUE TITLE
Other assets missing?

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#101]

**Comment by samreid** [comment]
I only see AI files from the pull_figures checked in, there are many (20+) other images from authors such as Noah, Open Clip Art, from Balancing Act, Sharon, where there is no original artwork checked in.  Reassigning to @ariel-phet to decide what to do about this.

**Comment by ariel-phet** [comment]
@samreid can you please make a list here of the missing artwork? We might be able to track it down, and we can have some of it redrawn so we have an original file.

**Comment by samreid** [comment]
In 3ad07a00ff9f7b5e0cf2165e2cc444b8611faec6 I moved an svg file from images/ to assets/ for the brick tile.

Here are the other files for which I don't see any vector artwork:
Acceleration_Icon.png
cart.png
cloud1.png
crate.png
files.txt
Friction_Icon.png
fridge.png
girl-holding.png
girl-sitting.png
girl-standing.png
grass.png
ice_overlay.png
icicle.png
license.txt
man-holding.png
man-sitting.png
man-standing.png
Motion_Icon.png
mountains.png
mystery-object-01.png
pusher_0.png
pusher_1.png
pusher_10.png
pusher_11.png
pusher_12.png
pusher_13.png
pusher_14.png
pusher_2.png
pusher_3.png
pusher_4.png
pusher_5.png
pusher_6.png
pusher_7.png
pusher_8.png
pusher_9.png
pusher_fall_down.png
pusher_straight_on.png
rope.png
skateboard.png
trash-can.png
Tug_Icon.png
water-bucket.png

**Comment by samreid** [comment]
Here is a link to the license file so you can see the artists associated with each graphic:
https://github.com/phetsims/forces-and-motion-basics/blob/master/images/license.txt

**Comment by ariel-phet** [comment]
@oliver-phet is going to look into the physical backups we have to see if we can locate the .ai files for this sim and EFAC

**Comment by ariel-phet** [comment]
We now have new vector artwork for the pusher and the man and girl (done by Mariah and checked in by @jessegreenberg). @jessegreenberg is also going to generate new screen icons (for which he can make a note about being made from screenshots).  I should be able to whittle the list down to:

cart.png
cloud1.png
crate.png
files.txt
fridge.png
grass.png
ice_overlay.png
icicle.png
license.txt
Motion_Icon.png
mountains.png
mystery-object-01.png
rope.png
skateboard.png
trash-can.png
Tug_Icon.png
water-bucket.png

**Comment by ariel-phet** [comment]
@jessegreenberg I think I have taken care of everything necessary here, can you look it over and if all look good close (or if more is needed assign back to me).

**Comment by jessegreenberg** [comment]
Looks good @ariel-phet, just checked and each file in images has a corresponding .ai file in assets.  Added notes about icon generation in images license, and added assets for sitting/standing/holding girl and man.  Closing.
