### ISSUE TITLE
Unify the slider look + feel + implementation

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#104]
FAMB uses a custom slider because it was written before (or at the same time) as our modern slider was being developed. It has custom features like being able to gray out half of the slider track, but it would be good to unify this as much as possible with the look + feel + implementation of our main slider.

**Comment by samreid** [comment]
@ariel-phet do you want to address this as part of the S2015R?  The implementation will likely remain independent (unless) but we could spend 2-4 hours making this slider look a bit more like the standard sun one.

**Comment by ariel-phet** [comment]
@samreid - seems like a good topic for developer meeting next week, I would like some other opinions.

**Comment by samreid** [comment]
from July 30 developer meeting:

AP: Simplifies tandem & accessibility to unify as much as possible.
SR: Sounds good, let’s go for it.  We can also try to implement this in a way that doesn’t complicate HSlider too much.

**Comment by samreid** [comment]
Unassigning this for now.  I'll reassign it when we start reworking forces and motion basics for the Summer 2015 Redeploy.

**Comment by jessegreenberg** [comment]
This should be completed before continuing with other slider related work in #142.

**Comment by jessegreenberg** [comment]
It looks like the features that forces-and-motion-basics\HSlider has that sun\HSlider does not have include:

- zero on release
- gray out one side of the slider to restrict one section

These will both be used in energy-forms-and-changes sliders as well.  From the above comments, it looks like the decision was to add these features to sun\HSlider.

I will create an issue in sun to monitor progress on these issues.

**Comment by jessegreenberg** [comment]
Sliders in FAMB now use sun/HSlider, so the implementation is unified.  Unsure how much of the look and feel should change for sliders in this sim.  Noticing a translation issue for the thumb, if the user clicks on Thumb and then drags right, the thumb will first snap left and then continue dragging.

**Comment by jessegreenberg** [comment]
> Noticing a translation issue for the thumb, if the user clicks on Thumb and then drags right, the thumb will first snap left and then continue dragging.

This is because the origin of the SliderKnob is different from the default HSlider ThumbNode.

**Comment by jessegreenberg** [comment]
Fixed in commit above.

**Comment by jessegreenberg** [comment]
Adding the 'ready for review' label in case layout, look, or feel of slider needs to change before redeploy.

**Comment by jessegreenberg** [comment]
One file thing before this can be closed: The 'thumb' needs to look disabled when the slider is disabled.

**Comment by jessegreenberg** [comment]
Done in commit above.  Further pixel polishing will be part of #166.
