### ISSUE TITLE
Backwards Sliding

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#108]
If either the girl or man are placed on an object that is already moving to the right, they will not change the way they are facing and will continue to face towards the left. This is in contrast with first placing the girl or man then applying force where the two will then turn to face to the right. This ends up looking strange when the girl or the man are the only object on the track and are sliding backwards.

https://drive.google.com/file/d/0B3HJopSo_QqLUkl6MkNBbVlBSTg/view?usp=sharing 

Seen on the published version and 1.1.0-rc.1 with Windows 8.1.
Troubleshooting information:
Name: Forces and Motion: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.0-rc.1/forces-and-motion-basics_en.html
Version: 1.1.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jessegreenberg** [comment]
Fixed in commit above, closing.
