### ISSUE TITLE
Chrome lag on cursor change

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#109]
This sim suffers greatly from phetsims/scenery/issues/275 even now with Chrome 39.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery/issues/275 Was closed.  I will verify that I can no longer reproduce this before closing the issue.

**Comment by jessegreenberg** [comment]
Seems like this is no longer an issue.  Closing.
