### ISSUE TITLE
remove TEMPORARY SCENERY WORKAROUND

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#115]
Scenery currently has an issue that crashes the sim in certain circumstances if opacity is used.  I am commenting out those parts so I can continue developing in master and marking them with

```js
// TEMPORARY SCENERY WORKAROUND
```

When the issue in scenery is fixed, the workarounds can be removed.

**Comment by jonathanolson** [comment]
Please try removing the workaround, I believe it should be fixed.

**Comment by samreid** [comment]
Looks great @jonathanolson, nice work!
