### ISSUE TITLE
Failure dragging puller (PropertySet related)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/forces-and-motion-basics#117]
Calls PropertySet.prototype.get.call( this ) for Item.js line 70. Fails on 2nd screen trying to drag the puller.

@samreid and @pixelzoom, was there an Axon change where this call was missed?

**Comment by samreid** [comment]
I couldn't reproduce the crash, but I think get=>getValues in PropertySet.  I'll rename it here.

**Comment by samreid** [comment]
Fixed in 741e488a28afedbc7181b9156708bdf10060dfe5  But can @jonathanolson double check this since I was never able to create the crash situation?

**Comment by jonathanolson** [comment]
Works well now, closing. Thanks!
