### ISSUE TITLE
focusable:true should be set in sun.ToggleNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#118]
FAMB.GoPauseButton is a subtype of sun.ToggleNode, and does:

> 73 focusable: true

This should be handled in sun.ToggleNode, as is done for sun UI components that use RoundButtonView and RectangularButtonView.

**Comment by jessegreenberg** [comment]
```focusable: true``` is no longer used by accessibility to add elements to the navigation order.  Input elements are implicitly included in the navigation order in the parallel DOM.

References in common code to ```focusable: true``` should be removed.  Issues in scenery, sun, and scenery-phet should be created and assigned to @jessegreenberg to handle this.

For the redeploy, all references to ```focusable: true``` in this sim should be removed.

**Comment by jessegreenberg** [comment]
Done in commits above.  See https://github.com/phetsims/sun/issues/225.  Closing.
