### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND for friction force?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#120]
Sim currently uses 'red' for friction force, which will appear black to many colorblind users. 

MotionScreenView, line 326:
>     this.frictionArrow = new ReadoutArrow( frictionForceString, 'red', this.layoutBounds.width / 2, 280, roundedFrictionForceProperty, model.showValuesProperty, {
      labelPosition: 'side',
      arrowScale: arrowScale
    } )

**Comment by samreid** [comment]
I'm going to unassign the issue for now--it will be addressed when I work on all Forces and Motion: Basics issues for the upcoming S2015R redeploy.

**Comment by jessegreenberg** [comment]
With the change to COLORBLIND_RED, the friction force arrow looks like:

![colorblind_red](https://cloud.githubusercontent.com/assets/6396244/13023693/7a8dccb0-d1a8-11e5-9b6e-6f95fd3466c7.PNG)

Removes the high contrast between Applied and Friction force arrows.  @ariel-phet is this a case where we can continue to use normal 'red'?

**Comment by jessegreenberg** [comment]
If we use PhetColorScheme.RED_COLORBLIND, a new icon image will also be required for the 'Friction' screen.

**Comment by jessegreenberg** [comment]
The Pause button also uses ```baseColor: '#df1a22'``` which is very similar to 'red'.

**Comment by jessegreenberg** [comment]
Colors of force arrows have high contrast when viewed in a gray scale.  @arouinfar what do you think, do we need to use PhetColorScheme.RED_COLORBLIND or change colors for color blindness and accessibility?

**Comment by arouinfar** [comment]
@jessegreenberg, I think we should stick with the red in the published version of the sim.

The contrast between the friction and applied force vectors is terrible when switching to colorblind red.
![image](https://cloud.githubusercontent.com/assets/8419308/13058868/53dbabae-d3e3-11e5-844d-82884167958b.png)![image](https://cloud.githubusercontent.com/assets/8419308/13058872/5a1983c4-d3e3-11e5-9641-8a73e56ff65a.png)

Comparing the two reds in the colorblind preview modes of Illustrator and at grayscale, the red currently in the simulation (left) always has higher contrast than colorblind red (right).
![image](https://cloud.githubusercontent.com/assets/8419308/13058936/fbf1d7c8-d3e3-11e5-8edc-ecccf2f01bdf.png)![image](https://cloud.githubusercontent.com/assets/8419308/13058942/040ff4e4-d3e4-11e5-838f-fff3b5105375.png)
![image](https://cloud.githubusercontent.com/assets/8419308/13058951/135c168a-d3e4-11e5-809e-d5b9c25080db.png)![image](https://cloud.githubusercontent.com/assets/8419308/13058952/1ae480a4-d3e4-11e5-8191-d09675cf1ac7.png)
![image](https://cloud.githubusercontent.com/assets/8419308/13059014/79e7f8f6-d3e4-11e5-9f44-90a39e8ddfc9.png)

**Comment by ariel-phet** [comment]
Sounds good, closing
