### ISSUE TITLE
id option?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#123]
I see option.id in several places (search for 'id:').  Eg:

MotionScreenView line 187:
> var itemsCentered = new Property( true, { id: 'itemsCentered' } );

Slider line 42:
> this.enabledProperty = new Property( true, { id: 'slider-enabled' } )

Property has no id option. Is this something vestigial?

**Comment by samreid** [comment]
Thanks, I removed it above.  Closing.
