### ISSUE TITLE
replace toFixed with dot.Util.toFixed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#135]
This sim uses JavaScript's built-in toFixed. This function should not be used directly; it is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Use dot.Util.toFixed, see its doc for details.

**Comment by samreid** [comment]
I'm going to unassign the issue for now--it will be addressed when I work on all Forces and Motion: Basics issues for the upcoming S2015R redeploy.

**Comment by jessegreenberg** [comment]
Done in the above commit, closing.
