### ISSUE TITLE
splash.svg error on startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#139]
When running in requirejs mode with brand=phet, I see this error in the console:

> GET http://localhost/~cmalley/GitHub/brand/images/splash.svg 404 (Not Found)

And the browser window looks like this while the sim is loading:

![screenshot_570](https://cloud.githubusercontent.com/assets/3046552/9212309/294d6ad0-4045-11e5-8106-6f63b6590a1e.png)

This problem may be unique to FAMB; I've tried other multi-screen sims and don't see this issue. What is FAMB doing that's different/unique?

**Comment by pixelzoom** [comment]
Chrome Version 44.0.2403.155 (64-bit) on Mac OS X 10.4.4.

**Comment by pixelzoom** [comment]
Same behavior on Firefox 40.0 and Safari 8.0.7 (10600.7.12) on Mac OS X 10.4.4.

**Comment by pixelzoom** [comment]
Here's the problem, in forces-and-motion-basics/forces-and-motion-basics_en.html:

```
<body bgcolor="black"><img id="splash"
                           style="position: absolute;top: 50%;left: 50%;margin-top: -180px;margin-left: -252px;"
                           src="../brand/images/splash.svg">
```

energy-skate-park-basics and lingo have a similar problem. Other sims have an empty `<body>`, why do these sims attempt to load splash.svg?

**Comment by samreid** [comment]
Removed body content above.  At one point during development, I had splash screens for the requirejs modes to make the requirejs mode match the built version a little more closely.  This is no longer valuable and I've removed it.  Reassigning to @pixelzoom to review/discuss.

**Comment by pixelzoom** [comment]
I don't have anything further to discuss, closing.
