### ISSUE TITLE
Add AP as lead design in credits

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#141]
Usually, I do not care about such things, but in this particular case, I think it would be appropriate to list me as a lead designer for this sim along with NP.

**Comment by samreid** [comment]
I marked for S2015R so it will get done before we redeploy.

**Comment by ariel-phet** [comment]
:cool:

**Comment by samreid** [comment]
Fixed in my working copy, looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/11860953/4218ab90-a438-11e5-8bd1-379ea25967f9.png)

Committing shortly.

**Comment by samreid** [comment]
Committed above, @ariel-phet can you take a quick look and make sure everything is as desired?

**Comment by ariel-phet** [comment]
a few changes actually:

1. take me off the "team" since I am in the Lead Design category now
2. both Mariah Hermsmeyer and Sharon Siman-Tov should be in graphic arts
3. Put the QA team the same as arithmetic (since that will likely be who tests it when we get to the RC)

**Comment by samreid** [comment]
Fixed here:

![image](https://cloud.githubusercontent.com/assets/679486/11878316/473daae2-a4b2-11e5-8fb5-944e2fa88e47.png)

@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
Looking good, closing
