### ISSUE TITLE
Add play/pause button

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#142]
From a user describing a use case (from the Java version) where the play pause button is very useful:

>What I do is ask  the students to start a push force on a frictionless surface at the same time the student starts a stop watch to measure the time from 0 m/s to 40 m/s.  They then calculate the change in velocity divided by time to get the acceleration.  They plot mass vs acceleration and force vs acceleration for changing masses and changing forces to see the relationships in F=ma.  Then we introduce friction with various push forces, and they calculate the appropriate accelerations.  Then based  on previous measurements without friction, the can determine what the force of friction must be to create the accelerations they observe.  Once they do that, the add a push force equal to the friction force to “check” that their calculations are correct and get no movement.  I have attached  the lab instructions for you.
>Again the key is being able to control the start of the push force so students can get an accurate time measurement.
>I would love for that start stop button to be on the HTML version!

I believe we removed the play/pause because of complications when we were first converting sims to HTML5 (and not wanting to put the play/pause close to other controls). However I think we could put these controls near the reset all button under the control panel as we have done in other sims.

@samreid - with our current framework would it be easy to add a play/pause button?

**Comment by samreid** [comment]
Yes, it would be straightforward.

**Comment by samreid** [comment]
@ariel-phet let's confirm details before I start.  

* add a play/pause toggle button to the left of the reset button, centering the PLAY + RESET box under the control panel.

* The simulation currently requires you to keep dragging the slider or pusher in order to continue applying force.  Shall we change it so that if you apply force while it is paused, then the applied force wouldn't go back to zero?  Or should the user have to use the tweaker buttons?

**Comment by ariel-phet** [comment]
@samreid yes play/pause to the left of the reset button (we should probably have a step button as well...it seems we always do a step button if we have a play/pause button). So I think the play/pause and step should feel grouped together, and I think the reset all button could be reduced in size slightly (10 or 15 percent)

I think we want the use to use the tweaker buttons in the use case you suggest. The reason the slider must be held is to help reinforce that to keep accelerating you must continue to apply a net force.

**Comment by ariel-phet** [comment]
@samreid hmm, actually, I just played with the java version...and there we had the interaction you describe. If you pause and then set the force and press play the force holds its value. Perhaps this makes sense, otherwise when you press play the force will be on for some slight moment and then go to zero. I am guessing that this could also cause inconsistent results depending on how the step in the model goes.

So, maybe we should go with the java paradigm that you suggest. It seems like it is for a pretty specific use case, and will not cause the issues.

**Comment by samreid** [comment]
@ariel-phet can someone else help with this issue?

**Comment by ariel-phet** [comment]
@jessegreenberg I am going to have you take over FAMB issues for redeploy since you are now quite familiar with this sim. FAMB should be prioritized after Trig Tour.

**Comment by jessegreenberg** [comment]
Added the play/pause and step buttons.  Currently, their positioning is constant for each screen.  Here is what it looks like:
![motion](https://cloud.githubusercontent.com/assets/6396244/12799637/1f5e997c-ca8d-11e5-9e3a-6659ec5fa793.PNG)
![frictionn](https://cloud.githubusercontent.com/assets/6396244/12799639/214d2208-ca8d-11e5-984d-f037a1d727a3.PNG)
![acceleration](https://cloud.githubusercontent.com/assets/6396244/12799641/223eaaa6-ca8d-11e5-8e7b-ef4e7819c2c3.PNG)


Should we give them some more space for the friction and acceleration screens?

**Comment by jessegreenberg** [comment]
Currently, the items do not animate to the center or their toolboxes unless model is playing.  They should animate to the correct location while paused, as in the Java version.

Also, the pusher force is maintained while paused, but not the slider.  This will need to be fixed as well.

**Comment by jessegreenberg** [comment]
While investigateing https://github.com/phetsims/forces-and-motion-basics/issues/138, sum of forces are also not calculated while sim is paused.

**Comment by jessegreenberg** [comment]
Item step functions fixed in commits above, still need to fix slider behavior to match the Java sim.

**Comment by jessegreenberg** [comment]
After discussion on 2/15/16, play/pause buttons should be aligned closer to the edges of the MotionControlPanel.

**Comment by jessegreenberg** [comment]
Buttons with new layout:
![capture](https://cloud.githubusercontent.com/assets/6396244/13058591/70a2a0f0-d3e1-11e5-8901-9f0fec5f64d1.PNG)

**Comment by jessegreenberg** [comment]
Wondering if the play pause buttons order should be switched so that the reset button is on the same side of the control panel for all four screens.  For the 'Net Force' screen, the reset button is on the right side of the panel.  To be discussed in a review meeting.

**Comment by jessegreenberg** [comment]
As mentioned in https://github.com/phetsims/forces-and-motion-basics/issues/166, the HSlider should *not* snap to zero when the sim is paused and dragging the pusher should resume play of the simulation.

**Comment by jessegreenberg** [comment]
Layout will be adjusted slightly as part of #166.

**Comment by oliver-phet** [comment]
Another request for this feature was received via phethelp on 4/4.

**Comment by jessegreenberg** [comment]
This feature has added and the layout was checked in #166.  Closing.
