### ISSUE TITLE
Consider difference between coefficient of static and kinetic friction 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#143]
A teacher wrote to phethelp about this concern but it has also been on my mind:

>I have a slight problem with how friction is depicted in this scenario. In Forces in 1-D simulation, it clearly shows that when static friction is overcome, that the kinetic friction is much lower. I am trying to teach my students this concept, but on the Force and Motion Basics sim, the static friction and kinetic friction are exactly the same value. We only have Chromebooks now, so I must use this sim.  

When we first designed the sim, it was really meant for younger students, but it seems to be such a powerful sim that it has gained adoption at much higher grade levels. I have even used it many times for introductory physics at the college level.

We originally decided to make static and kinetic friction have the same coefficient, which was a simplifying assumption. However, this assumption does limit the utility of the sim a bit, and it also does conflict with one of our goals to make connections to the real world.

@samreid how involved of a change to the model would it be to make a rule that the moment the object goes in motion and friction is present the coefficient of kinetic friction is scaled to be 75 percent the value of static friction?

**Comment by samreid** [comment]
@ariel-phet requested a time estimate for this work.

**Comment by samreid** [comment]
@ariel-phet Are we talking about all 4 screens, or just the latter 3?

**Comment by samreid** [comment]
Or just screens 3-4 I suppose? (screen 2 has no friction).

**Comment by samreid** [comment]
Adding the `*0.75` at the end of this line may be sufficient, seems good in my limited tests:

```js
      //Object is moving, so friction should oppose the velocity
      else {
        return -this.getSign( this.velocity ) * frictionForceMagnitude * 0.75;
      }
```

However, testing is somewhat limited due to #147

**Comment by samreid** [comment]
#147 fixed, the behavior seems reasonable to me and I'll commit this change to master and publish a dev version for @ariel-phet to review.

**Comment by samreid** [comment]
Published a dev version here: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.5-dev.11/forces-and-motion-basics_en.html

@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
@samreid I think this is looking good. I will plan on bringing up at design meeting, but I am thinking this will be a good change.

**Comment by arouinfar** [comment]
@samreid @ariel-phet I think this is an excellent change to the sim.

**Comment by ariel-phet** [comment]
Design meeting Nov 19 2015 @kathy-phet agrees this is a reasonable change, closing.
