### ISSUE TITLE
When a puller is focused within a group, pressing Tab key should put focus on the next item in tab order

### ISSUE THREAD

**Issue by jhung** [phetsims/forces-and-motion-basics#146]
When focus is on a puller within a group, pressing Tab should move focus to the next item in the tab order. Currently pressing tab puts focus back on the parent container which is inconsistent with conventions.

Example:
1. Tab focus the left group.
2. Press enter
3. Press Tab again
4. Notice focus is on the Left group, but expectation is for focus to move to the Right group.

Aside, the current behaviour for pressing ESC key is correct i.e. focus "backs out" back to the parent container.

**Comment by samreid** [comment]
@jessegreenberg can you comment on this?

**Comment by jessegreenberg** [comment]
@jhung, thanks for pointing this out,  I completely agree.  In addition to being more conventional, this also removes an unnecessary extra key stroke.

This fix was added in a recent  version published here:
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.1.5-accessible-instance.5/forces-and-motion-basics_en.html?accessibility&screens=1

Pressing `tab` should exit the puller group and immediately focus the next group or item in the navigation order.

I have been considering using aria-activedescendant or html fieldsets for these kinds of nested groupings.  These would also behave as suggested above, where pressing `tab` would exit the group and place focus on the next element.  Either of these options might be more conventional and simplify the code. However, with these options we might lose the ability to focus on the entire grouping as a whole.  It would be a different style of interface, but worth considering.

**Comment by jessegreenberg** [comment]
This has been implemented and is in the most recent dev version of accessible forces and motion basics.

Closing for now.
