### ISSUE TITLE
Publish social media posts when republished

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#150]
@kathy-phet requested that when we republish FAMB with the change suggested in #143 we push stories to our social media about how this change was influenced by teacher feedback.

**Comment by jessegreenberg** [comment]
@ariel-phet assigning this to you now since the FAMB was republished.

**Comment by ariel-phet** [comment]
@kdessau-PhET I have started tweeting about this, might be good to have some FB posts as well. Basically teachers requested the following:
1. A play/pause button on the motion screens (as in the Java sim) to allow for setting up experiments
2. A difference between the coefficient of static and kinetic friction
3. Readouts for speed and acceleration so students could do more quantitative calculations

All were added to the version now up on the website. i will be parsing those up and tweeting about it over the next week or two, but you could probably write a single comprehensive post.

**Comment by kdessau-PhET** [comment]
Got it. i will write a single piece and post on FB on Monday.

**Comment by jessegreenberg** [comment]
@ariel-phet and @kdessau-PhET can this issue be closed?

**Comment by ariel-phet** [comment]
Yes, closing
