### ISSUE TITLE
Show acceleration readout when "Values" checked

### ISSUE THREAD

**Issue by arouinfar** [phetsims/forces-and-motion-basics#153]
We received the following suggestion from a teacher on Facebook

> I don't know if this is a good place to give feedback on particular sims but here goes:  I like "Forces and Motion: Basics" a lot.  Why, oh why, can't you display the actual acceleration instead of just a gauge, though?  And if it has to be a gauge, why is that gauge demarcated only as a maximum with no intermediate tick marks?  I'd love to use this as an inquiry into Newton's Second Law but it's difficult to read the acceleration, obviating the whole point.

Since this is the “Basics” version of the sim, I imagine we deliberately decided not to quantify the acceleration (though the max/min is labeled with a unitless +/- 20).  Quantifying the acceleration would facilitate broader learning goals related to Newton's 2nd Law. Given that a port of FAM is not on the horizon, we should address this issue with the redeploy (similar to how we addressed #143). 

@ariel-phet suggested
> My suggestion would be simply that if "values" is checked that to the right of the word acceleration on the meter some sort of readout, perhaps in parentheses just gives the actual value such as "Acceleration (20.1 m/s^2)"

I would also like to see the addition of an acceleration readout. Here's a mockup of the current version (top) and the proposed change (bottom).

![image](https://cloud.githubusercontent.com/assets/8419308/12465066/85bb2e6a-bf89-11e5-8c6a-0187e1aa8a9e.png)

**Comment by jessegreenberg** [comment]
While looking into this, I noticed that 'Acceleration' is hard coded into the screen view, it is not translatable.

**Comment by jessegreenberg** [comment]
Done in the above commit, 

![acceleration](https://cloud.githubusercontent.com/assets/6396244/12798416/828ec960-ca86-11e5-915d-ba182a531fa0.PNG)
![acceleration units](https://cloud.githubusercontent.com/assets/6396244/12798418/857516d4-ca86-11e5-9d5c-16a4f4c50b44.PNG)

**Comment by samreid** [comment]
@ariel-phet after seeing this I am wondering what you think about removing the parentheses.

**Comment by ariel-phet** [comment]
Perhaps, I need to look at it in context, self assigning for the moment

**Comment by arouinfar** [comment]
@ariel-phet here are a few options to consider.

![image](https://cloud.githubusercontent.com/assets/8419308/12800538/10845238-ca93-11e5-93dd-01887f32b4b7.png)

**Comment by arouinfar** [comment]
On second thought, the two-lined approach won't work. I had the speedometer off initially, so I didn't realize how little real estate we have to work with in this case. 

![image](https://cloud.githubusercontent.com/assets/8419308/12800571/58cc09be-ca93-11e5-8615-76e4f956ab98.png)

**Comment by ariel-phet** [comment]
Thanks for the options @arouinfar 

@jessegreenberg lets try "Acceleration: XX"  (and of course, the ":" should only appear with when the value is dispalyed

**Comment by arouinfar** [comment]
Good suggestion @ariel-phet! I think the colon will be the best option.

**Comment by jessegreenberg** [comment]
Here it is with the colon:

![accelerationcolon](https://cloud.githubusercontent.com/assets/6396244/12830953/2e3ab382-cb4f-11e5-86c7-646d310ca037.PNG)

Look good @arouinfar @ariel-phet?

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg!

**Comment by jessegreenberg** [comment]
Great! Closing.

**Comment by jessegreenberg** [comment]
On second thought, this was a teacher request so perhaps this should be publicized or something when the sim is redeployed?  Not sure, but reassigning to @ariel-phet to close or track for issue #150.

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar 

It seems for consistency, there is no obvious reason to not display the speed quantitatively when "values" are checked and the speedometer is also active. I think we could just display the speed (in m/s) in the bottom portion of the speedometer) perhaps in a readout? Like:

![speedometer](https://cloud.githubusercontent.com/assets/4051174/12903129/84727358-ce82-11e5-9cf3-f9e51d6e39f6.png)

**Comment by arouinfar** [comment]
I think that's an excellent suggestion @ariel-phet!

**Comment by samreid** [comment]
Sounds good, I would see what this looks like without a border--may be a bit cleaner.  Also I'm thinking you'll need one decimal place as well.  And m/s may become longer in other languages so this will need to be scaled down.

**Comment by ariel-phet** [comment]
@samreid - The reason I think a border is good here is then it looks like a normal speedometer in a car, I think the border can be pretty lightweight (thin stroke and probably a shade of grey), but I do think it should be there.

**Comment by samreid** [comment]
I get the speedometer analogy and think it's a good analogy, still wanted to see if it is cleaner without a border:

![image](https://cloud.githubusercontent.com/assets/679486/12903623/582dd3c4-ce86-11e5-9683-f4b3d2d28fc2.png)

Seems a bit less "organized" without the box, so I agree to keep it.

**Comment by jessegreenberg** [comment]
Added, here it is in the simulation with the border and one decimal place.

![speed](https://cloud.githubusercontent.com/assets/6396244/12905796/7817754e-ce97-11e5-8536-0b1de673bc8d.PNG)

Reassigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looked at the latest pull

@jessegreenberg the look was good, I think we can close this issue (though I will note the speed readout was appearing even if values was not checked). So perhaps fix that, then close this issue.

**Comment by ariel-phet** [comment]
Also please add a bit of negative space between the acceleration readout and the speedometer (move the acceleration readout down)

**Comment by ariel-phet** [comment]
Oh...and...speed should probably always be a positive value (since we are labeling it speed, not velocity), and the speedometer only shows magnitudes.

**Comment by jessegreenberg** [comment]
> though I will note the speed readout was appearing even if values was not checked

Gah, sorry.  Fixed in https://github.com/phetsims/forces-and-motion-basics/commit/fc684aa254cf80fca0a0bc2b6c03e065d150a4d0

> Also please add a bit of negative space between the acceleration readout and the speedometer (move the acceleration readout down)

> speed should probably always be a positive value

Done in https://github.com/phetsims/forces-and-motion-basics/commit/ce46bb283959b504f9e05253e4614a6b90ac292c

Not a whole lot of vertical space to play with since the acceleration readout is sandwiched between the speedometer and the 'Sum of Forces' readout. 

![sum of forces](https://cloud.githubusercontent.com/assets/6396244/12966103/aa684708-d018-11e5-9e8b-2ca85176da72.PNG)

This acceptable @ariel-phet?

**Comment by jessegreenberg** [comment]
In a meeting on 2/15/15, it was suggested that the accelerometer and speedometer:

-  [ ] Should initially and always be located to the left of the item stack
-  [ ] Should have a little more vertical space

**Comment by jessegreenberg** [comment]
These features were added.  Pixel polishing for this issue is being completed in https://github.com/phetsims/forces-and-motion-basics/issues/166.  Closing.
