### ISSUE TITLE
Uncentered objects

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#154]
With increasing string length, the objects on the last three screens become more and more uncentered. This is very obvious with ?stringTest=long, but still happens with =double.

![famb long](https://cloud.githubusercontent.com/assets/5863899/12466699/95b2706c-bf93-11e5-88f3-8a37038f1910.PNG)

Tested on phetttest with Win 8.1 FF. For phetsims/tasks/issues/479

Troubleshooting information:
Name: 12345678901234567890123456789012345678901234567890
URL: http://phettest.colorado.edu/forces-and-motion-basics/forces-and-motion-basics_en.html?ea&brand=phet&stringTest=long
Version: 1.1.5-dev.13 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Aha, it looks like the mass labels are scaled with the images but not centered.

**Comment by jessegreenberg** [comment]
Note quite.

```js
item.animateTo( motionView.layoutBounds.width / 2 - itemNode.width / 2 + item.centeringOffset, motionView.topOfStack - itemNode.height, 'stack' );
```
itemNode.width is dependent on the width of the translated label.  The length of the label can change the destination of the itemNode in animateTo.

**Comment by jessegreenberg** [comment]
ItemNode transforms assume that the origin of the node is at the upper left corner of the *image*.  Since the label can extend beyond the width of the image, 

```js
motionView.layoutBounds.width / 2 - itemNode.width / 2
```

the translation is too far to the left because ```itemNode.width / 2``` is an incorrect correction since the translation is relative to the width of the image.

**Comment by jessegreenberg** [comment]
For the correct interaction, two scales are applied at different times to the ItemNode.  ```interactionScale``` and ```item.imageScale```.  In every call to animateTo, we want to correct for the width of the image, not the width of the whole itemNode.

I think the translation to the center of the screenView should be something like:
```js
item.interactionScale * item.imageScale * normalImageNode.width / 2
```

Need to test for all of the items.

**Comment by jessegreenberg** [comment]
The above scaling calculation is correct, but it looks like it will need to be used in several places in the simulation.  ```animateTo``` is not the only place where the scale is applied.  For instance, the puller looks for the edge of the ItemNode, not the edge of the scaled item image.

![offset](https://cloud.githubusercontent.com/assets/6396244/12896094/517277de-ce5d-11e5-8646-da85d50abd97.PNG)

**Comment by jessegreenberg** [comment]
This issue is resolved with the above commits.  Closing.

**Comment by jessegreenberg** [comment]
Prematurely closed.  Transformation issues for the mass labels were fixed but there are still a few i18n issues present that need to be fixed.

**Comment by jessegreenberg** [comment]
Gah, wrong issue.  Closing.
