### ISSUE TITLE
Return button lost with stringTest=double

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#155]
With increasing string length, the "Go" button resizes and pushes the "Return" button off the bottom of the screen (you can see its pointer areas in the nav bar):

![famb dubs](https://cloud.githubusercontent.com/assets/5863899/12466825/64b16526-bf94-11e5-9cf0-ef5798b576bf.PNG)

Tested on phetttest with Win 8.1 FF. For phetsims/tasks#479

Troubleshooting information:
Name: 12345678901234567890123456789012345678901234567890
URL: http://phettest.colorado.edu/forces-and-motion-basics/forces-and-motion-basics_en.html?ea&brand=phet&showPointerAreas&stringTest=double
Version: 1.1.5-dev.13 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Fixed in the commit above, closing.

![stringtest](https://cloud.githubusercontent.com/assets/6396244/12765883/f9b7823a-c9bd-11e5-974f-55170230ad75.PNG)
