### ISSUE TITLE
Update Screen Selection icons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#164]
Now that the girl and man 'holding' images have been updated in https://github.com/phetsims/forces-and-motion-basics/issues/137, @amyh-phet pointed out that the 'motion' screen icon is out of date.  We will want to update this icon so that the icons and screen match in look and style.

**Comment by ariel-phet** [comment]
All the screen icons (motion, friction, acceleration) should be updated.

However, https://github.com/phetsims/tasks/issues/501 needs to be completed and integrated into the sim before this update, unassigning until artwork is complete

**Comment by jessegreenberg** [comment]
Handling this as part of #166.

**Comment by jessegreenberg** [comment]
Icons updated, but leaving this issue open until they are reviewed in #166.

**Comment by jessegreenberg** [comment]
#166 was closed so this issue can be as well.
