### ISSUE TITLE
Pixel Polishing for Redeploy

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#166]
On 3/3/16 @jessegreenberg met with @ariel-phet to discuss some pixel polishing that needs to be done before the redeploy of Forces and Motion: Basics.  This issue will track those items:

- [x] Bring up items in the toolboxes vertically to give some more space between the item and bottom of toolbox.  Shrink man vertically to compensate and increase size of fridge to match size of man.

- [x] Dilate the play button when the sim is paused.
- [x] Buttons on acceleration screen should be vertically centered between control panel and ground (this will define the vertical spacing of play/bause/reset buttons for the reset of the sim screens
- [x] Scale down the pause button just a bit

- [x] Size of reset all button on motion and net force screens should be the same, make up difference between the two

- [x] Little more space between buttons and control panel on Net Force screen

- [x] When sim is paused, HSlider should not snap

- [x] 'Acceleration readout' layout should not change when value changes

- [x] When the user interacts with the pusher, the sim should automatically start playing again if paused

- [x] Lock sum of forces label in place, it should not translate vertically

- [x] Acceleration readout label should not shift when the value changes sign

- [x] New icons for the screens
    - Match what is already there with updated assets

- [x] Add @arouinfar to team credits

- [x] Move the gauge node down just a bit

- [x] 'Values' checkbox should be moved out from under 'Forces' checkbox.  Sum of Forces checkbox should be disabled when 'Forces' Checkbox is not checked.

  - [x] EDIT: Check box should not be disabled, and 'Sum of Forces' can be visible when force vectors are invisible, See https://github.com/phetsims/forces-and-motion-basics/issues/167

**Comment by jessegreenberg** [comment]
> Sum of Forces checkbox should be disabled when 'Forces' Checkbox is not checked.

MotionControlPanel uses VerticalCheckBoxGroup whhich does not support disabled check boxes.  For this feature, we either need to support disabled check boxes in VerticalCheckBoxGroup, or create custom VBoxes for the check box groups.

**Comment by jessegreenberg** [comment]
VerticalCheckBoxGroup is to phase out in preference for a general layout strategy (https://github.com/phetsims/sun/issues/30).  To handle disabled checkboxes, we will need a new control panel that uses VBoxes instead of VerticalCheckBoxGroup.

**Comment by jessegreenberg** [comment]
> we will need a new control panel that uses VBoxes instead of VerticalCheckBoxGroup.

Done via https://github.com/phetsims/forces-and-motion-basics/commit/eab5af8571150134768b616660bd06dd6f77c9b8

**Comment by jessegreenberg** [comment]
'Sum of Forces' check box disabled when 'Forces' check box unchecked.

**Comment by jessegreenberg** [comment]
> When the user interacts with the pusher, the sim should automatically start playing again if paused

Done with commit https://github.com/phetsims/forces-and-motion-basics/commit/936f00ac2b3dafe0010e3607ae12a0692d696299.

This was done to prevent the sim from seeming broken if it is paused.  But I wonder if it could be frustrating to users that are trying to set a state of forces with the pusher when the sim is paused.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/forces-and-motion-basics/commit/eea0feb665a1afdfd5cda80a0357ae772b1f05af completes

> Lock sum of forces label in place, it should not translate vertically

**Comment by jessegreenberg** [comment]
> Sum of Forces checkbox should be disabled when 'Forces' Checkbox is not checked.

This is no longer desired, see https://github.com/phetsims/forces-and-motion-basics/issues/167

**Comment by jessegreenberg** [comment]
All items in checklist completed.  Here is a dev version where these items can be reviewed:
http://localhost:8080/forces-and-motion-basics/forces-and-motion-basics_en.html

Assigning to @ariel-phet to review.

I will also submit this version for dev testing.  At this point many features have been added and should be tested before an RC.  Remaining issues for the redeploy should be minimal and can be added before the RC for the deploy.

**Comment by jessegreenberg** [comment]
In 3/17/16 stattus meeting @ariel-phet reported some performance issues on his machine as well as a layout issue on the 'Friction' screen for the check boxes now that their layout has changed.  These issues should be addressed before a dev version is reviewed and tested.  Reassigning to myself.

**Comment by jessegreenberg** [comment]
#172 is the last issue that needs to be investigated before a dev version is ready for review and testing.

**Comment by jessegreenberg** [comment]
The version id needs to be bumped for this version as well.

**Comment by jessegreenberg** [comment]
@ariel-phet here is the dev version that was submitted for dev testing:
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.1/forces-and-motion-basics_en.html

Would you please also review the new features in this version and review the pixel polishing changes associated with this issue?  Let me know if any further changes are necessary.

**Comment by phet-steele** [comment]
@jessegreenberg, the thumb of the sliders was never updated to the common one. FAMB has a unique looking thumb with six little dots. Do we want to change this to the normal thumb?
![thumb](https://cloud.githubusercontent.com/assets/5863899/14191595/d83a211a-f755-11e5-8b7f-cc049bd91cb2.PNG)

**Comment by ariel-phet** [comment]
@jessegreenberg a few either minor pixel polishes

- [ ] On the motion screen, expand the control panel horizontally a bit (as shown in mockup below). I think this gives a better separation and grouping to the play/pause buttons
- [ ] On motion, friction, and acceleration screens left align play button with left edge of control panel, and right align reset all button with right edge of control panel (as shown in mockup below)

![famb](https://cloud.githubusercontent.com/assets/4051174/14198915/8302e9ce-f79c-11e5-9e88-eaef7542ef1c.PNG)

**Comment by jessegreenberg** [comment]
> Do we want to change this to the normal thumb?

I asked @ariel-phet this a few weeks ago, and we decided to keep this custom thumb style for the motion screens.

**Comment by phet-steele** [comment]
@jessegreenberg :+1:

**Comment by jessegreenberg** [comment]
> For case when friction force and applied force are in the same direction move the "Friction Force" label up to be closer to the friction arrow,

Done in above commit.  This removes the overlapping with the 'masses' label, but the friction force value is a bit harder to read now.
![capture](https://cloud.githubusercontent.com/assets/6396244/14223671/114353d8-f840-11e5-8e6d-38759cf1c824.PNG)

**Comment by jessegreenberg** [comment]
@ariel-phet here is a dev version with these changes:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.2/forces-and-motion-basics_en.html

Assigning to you again for review.

**Comment by ariel-phet** [comment]
@jessegreenberg two things:

1. How about in that overlapping case if you just right "94 N" to the right of "Friction Force" I think that will make it easier to read and not have much interference with other things

2. On the motion screen it looks like objects are sitting a pixel or two too low on the skateboard instead of right on top of it

![box](https://cloud.githubusercontent.com/assets/4051174/14223903/dc9f30a0-f846-11e5-8256-29f2954b4d48.PNG)

**Comment by ariel-phet** [comment]
BTW, this slight misalignment exists in the deployed version (but seems like it would be good to fix)

**Comment by jessegreenberg** [comment]
@ariel-phet here is a new dev version with these changes.  Would you mind reviewing this version and letting me know if anything else needs to be adjusted?

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.2/forces-and-motion-basics_en.html

**Comment by ariel-phet** [comment]
@jessegreenberg all looks great! Closing
