### ISSUE TITLE
Gray out Sum of Forces checkbox when Forces unchecked?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/forces-and-motion-basics#167]
I've been playing with dev.15 to get the Teacher Tips ready to post with the redeploy. I've noticed that it is not possible to see the Sum of Forces independently of Forces. However, the Sum of Forces checkbox remains active and can be turned on/off while Forces is unchecked. The published version of the sim behaves the same way.

I find this behavior to be a bit problematic, because users may expect the Sum of Forces to be displayed on the screen when it is, in fact, an inactive option.

![image](https://cloud.githubusercontent.com/assets/8419308/13745690/20294a5c-e9f8-11e5-9000-bacc45e9fccc.png)![image](https://cloud.githubusercontent.com/assets/8419308/13745676/0f55090a-e9f8-11e5-8171-544902571282.png)

In other simulations, nested options whose visibility depends on its parent are grayed out when inactive, as in Charges & Fields and Hooke's Law.
![image](https://cloud.githubusercontent.com/assets/8419308/13745615/bb19ebb2-e9f7-11e5-8bcc-7f23c91ea6a7.png)![image](https://cloud.githubusercontent.com/assets/8419308/13745620/c50d785a-e9f7-11e5-8209-4a050cd8226f.png)
![image](https://cloud.githubusercontent.com/assets/8419308/13745635/d4eca502-e9f7-11e5-8589-7d20755a6436.png)![image](https://cloud.githubusercontent.com/assets/8419308/13745645/e67a14d0-e9f7-11e5-9c88-f15bf3fad942.png)

I see two potential ways to address this issue. 
1. Gray out Sum of Forces checkbox when Forces is inactive.
2. Allow the Sum of Forces to be displayed, even when Forces is unchecked. 

I can imagine that some teachers may wish to display the sum of the forces without looking at the applied/friction components, so I have a slight preference for option 2. 

@ariel-phet can you please comment on this issue and reassign? As part of the original design team, I think you better understand the motivation behind keeping the Sum of Forces dependent on Forces being checked.

**Comment by jessegreenberg** [comment]
As part of https://github.com/phetsims/forces-and-motion-basics/issues/166, I have already implemented option 1 above.  

But @arouinfar makes good points for option 2, we could easily switch to that if necessary.

**Comment by ariel-phet** [comment]
@arouinfar I had been starting to think something similar, I think option 2 is a more flexible one. That allows the flexibility to ask predictive questions and such.

**Comment by jessegreenberg** [comment]
@ariel-phet and @arouinfar should the 'Sum of Forces' check box still be nested under the 'Forces' check box then?

**Comment by ariel-phet** [comment]
I think in that case, do not nest.

**Comment by arouinfar** [comment]
@ariel-phet thanks!

@jessegreenberg if you un-nest Sum of Forces, you may also want to do the same for Values, as it applies to the Speed and Acceleration too.

**Comment by jessegreenberg** [comment]
Good point @arouinfar, that was already done as part of #166 for that exact reason.

**Comment by arouinfar** [comment]
Looks like I should have reviewed #166 more carefully. :)

Thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
#166 was closed, so this one can be too.
