### ISSUE TITLE
Update 'Mystery Object' image?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#170]
The mystery object is the only item that does not line up with the pusher when it is being pushed on its own on the 'Friction' screen.  Is it worth updating this image?

![capture](https://cloud.githubusercontent.com/assets/6396244/13821200/3d94e1ae-eb66-11e5-9097-314b4a4dda6b.PNG)

**Comment by jessegreenberg** [comment]
Also, if this is done should it be added before the redeploy?

**Comment by ariel-phet** [comment]
@jessegreenberg yes...this does seem like it would be good to update. Besides the bow on the one has always been a bit poor quality. I will see if I can get you something soon.

And yes, would be good to add before redeploy

**Comment by ariel-phet** [comment]
@jessegreenberg I updated the .ai file 

https://github.com/phetsims/forces-and-motion-basics/blob/master/assets/mystery-object-01.ai

See if this new image works for you (I think it will be tall enough now, but will be easy to tweak if it needs to be bigger).

**Comment by jessegreenberg** [comment]
Size looks good to me:

![capture](https://cloud.githubusercontent.com/assets/6396244/13850782/12df9fce-ec21-11e5-80ed-3069b507a5d8.PNG)

Leaving open until reviewed with other items in a dev version as part of #166.

**Comment by phet-steele** [comment]
@ariel-phet @jessegreenberg still looks pretty low quality to me, even on the high rez retina displays. Compared to a box:
![fuzzybox](https://cloud.githubusercontent.com/assets/5863899/14261825/b5ff772c-fa6f-11e5-9358-2d5078b9ac81.PNG)

**Comment by jessegreenberg** [comment]
Asset image quality looks much better, so this is likely due to scaling issues.  I will investigate.

**Comment by jessegreenberg** [comment]
Looking much better now: 
![capture](https://cloud.githubusercontent.com/assets/6396244/14544388/0d119bc4-0256-11e6-8750-377e53943138.PNG)

**Comment by jessegreenberg** [comment]
Looking pretty sharp on both Windows and OSX Firefox!

**Comment by jessegreenberg** [comment]
Closing this issue, resolution of image improved.  If any resolution issues come out of dev/rc testing, new issues will be created.
