### ISSUE TITLE
Fix layout of 'Friction' control panel 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#173]
The check boxes in the control panels are centered in their layout.  This looks strange in the 'Friction' screen due to one element that has a larger width than the others.

To fix this, we should try to align the control panel items to the left to see how that looks.  This way control panel layout may match across screens.

**Comment by jessegreenberg** [comment]
For reference...

'Acceleration' Control panel:
![capture](https://cloud.githubusercontent.com/assets/6396244/13853769/e05bca7a-ec2d-11e5-9641-86df40451c63.PNG)

'Friction' control panel:
![capture2](https://cloud.githubusercontent.com/assets/6396244/13853773/e8b0d562-ec2d-11e5-865d-5e0305bbb44a.PNG)

**Comment by jessegreenberg** [comment]
Controls in panel are now aligned to the left. Layout after the change:

![capture-1](https://cloud.githubusercontent.com/assets/6396244/13995851/b7731bb4-f0f0-11e5-88c5-44def26c01fb.PNG)

![capture-2](https://cloud.githubusercontent.com/assets/6396244/13995852/bac93550-f0f0-11e5-99f0-7b2377a489a7.PNG)

**Comment by jessegreenberg** [comment]
Hmm on very close inspection,it looks a little strange to have the slider aligned to the left with the check boxes.  Maybe the slider should be centered in the panel while the check boxes are aligned to the left?

I will give this a try.

**Comment by jessegreenberg** [comment]
Changed the layout structure slightly so that the check boxes are aligned to the left of the panel, with the slider centered under them.

**Comment by phet-steele** [comment]
@jessegreenberg this fix is not in 2.0.0-dev.1, was it supposed to be? Check boxes are still centered. phetsims/tasks/issues/562

**Comment by phet-steele** [comment]
They don't appear to be centered aligned though, so that's good. With `?stringTest=double` they look decent:
![doublefriction](https://cloud.githubusercontent.com/assets/5863899/14191784/13624fd2-f757-11e5-9d62-1e5bdebcbaa9.PNG)

Default is what looks wrong:
![singlefriction](https://cloud.githubusercontent.com/assets/5863899/14191810/2dd1c726-f757-11e5-91f4-e833e4b16ab2.PNG)

**Comment by jessegreenberg** [comment]
Yes it was!  I merged with another branch right before publishing dev version, maybe something was botched in the merge.

**Comment by phet-steele** [comment]
@jessegreenberg fixed in 2.0.0-dev.2! :tada:

**Comment by jessegreenberg** [comment]
Great, thanks @phet-steele.

**Comment by jessegreenberg** [comment]
Verified as fixed, closing.
