### ISSUE TITLE
User suggestion: Add timer, simplify speedometer

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#174]
Dear Phet,

On the "Forces and Motion: Basics" simulation, I really like the speed dial that can show up.  I would like to make one suggestion or request.  

Could you add a timer?
Could you change speed calculations so that the dial represents simpler #'s?
 

I would like to be able to give my students the F=ma equation and the a=v/t equation and then use the app and timer to calibrate the clock or tell me what #'s should go on the big and little lines in the speed dial.  I like that no #'s are listed on the speed dial, because I want to ask the students to find out what #'s should go there.

So for example.  With a known force and mass, the acceleration can be calculated.  Then using (final velocity - initial velocity)/(final time -initial time)=a   a student could then use the F and m to get a and then use the timer to find final v.  Then they can calibrate the clock!

Currently the speed dial doesn't come out to be such a nice number for each unit on the dial.  It would be nice if each segment represented something like 5m/s just any whole  #  such as 7m/s at least.  

This would make for an awesome in depth lab.  Thanks.

**Comment by oliver-phet** [comment]
@ariel-phet Can you comment on this suggestion?

**Comment by ariel-phet** [comment]
@oliver-phet we will not be adding a timer to the sim, but you can let the user know that in an upcoming version (to be redeployed within a couple of weeks) the speedometer will have a readout option (if the "values" checkbox has been checked). 

In that version each tick mark represents 1 m/s (which seems like a very easy simple to interpret division)

**Comment by oliver-phet** [comment]
Emailed user. Closing.

**Comment by oliver-phet** [comment]
Just to document, another user requested a timer.

> I am a science educator and would find it WONDERFUL if you would add a TIMER/CLOCK to your Forces-and-motion-basics simulations, especially in the Motion and Acceleration sims, so students can keep track of time passed.  Would it be possible to add this in the near future?
