### ISSUE TITLE
Pusher not layered in front of skateboard

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#178]
As shown below you can see the pusher is not layered in front of the skate board, this causes an odd perspective when the pusher move across the skateboard.

To reproduce:
1. push on one side to get the object going a bit
2. push briefly on the opposite side and then remove force so object passes in front of stationary pusher

![layering](https://cloud.githubusercontent.com/assets/4051174/14198781/3fbd2ae0-f79b-11e5-80f6-a259a2e34f12.PNG)

**Comment by ariel-phet** [comment]
Related to https://github.com/phetsims/tasks/issues/562

**Comment by phet-steele** [comment]
@jessegreenberg it appears everything in this screen is layered behind the skateboard. This looks weird when dragging objects to be placed.

**Comment by phet-steele** [comment]
@mariahmaephet please mock up the new PhET Cyclops Girl :wink::
![cyclopsgirl](https://cloud.githubusercontent.com/assets/5863899/14215268/3c1baeb6-f7ff-11e5-85fb-a484dafb048a.PNG)

**Comment by jessegreenberg** [comment]
Pusher has been moved in front of skateboard.

![pusher](https://cloud.githubusercontent.com/assets/6396244/14222116/0734dd6e-f82a-11e5-8f2d-f579380fb657.png)

**Comment by jessegreenberg** [comment]
> it appears everything in this screen is layered behind the skateboard.

Fixed as well.  In the https://github.com/phetsims/forces-and-motion-basics/issues/178#issuecomment-204486397, it also looks like the items are behind the force controls, which is a deviation from the published version.

**Comment by jessegreenberg** [comment]
Item layering mostly matches the deployed version, and PhET girl is back to her usual self.
![layer](https://cloud.githubusercontent.com/assets/6396244/14222494/8300e4a2-f82e-11e5-891a-6588081e2208.PNG)

However, items from the right toolbox are layered in front of the items from the left toolbox.  This is a deviation from the deployed version, and was introduced in a restructuring for accessibility so that items are children of their toolboxes.

**Comment by jessegreenberg** [comment]
Fixed in commit above.  Layering should match deployed version except that now the pusher is in front of skateboard.

**Comment by jessegreenberg** [comment]
Here is a dev version with the new layering:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.2/forces-and-motion-basics_en.html

The only case it looks strange is when an item is dragged under the pusher:
![capture](https://cloud.githubusercontent.com/assets/6396244/14223704/5410e080-f841-11e5-9745-0424005f76fe.PNG)

Now that the items are in front of the skateboard again, layering would look 'correct' to have the pusher behind the items and the skateboard.  This is how the deployed version is layered.  @ariel-phet, would you like me to do this?

**Comment by ariel-phet** [comment]
Ah yes, looking at the deployed version, layering the pusher behind items and the skateboard works more naturally.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, pending testing.

**Comment by phet-steele** [comment]
@jessegreenberg 2.0.0-dev.2 pusher is in far back, skateboard is in the stack layer, and all dragged items are layered in the front. Nice! :+1:
