### ISSUE TITLE
Speed value intially reads "1.0 m/s" if nothing is touched

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#179]
Occurs on all motion screens

To reproduce:
1. Open one of the motion screens (motion, friction, acceleration)
2. Check "Speed" and "Values"
3. The speedometer will read "1.0 m/s" even though the object is stationary

related to https://github.com/phetsims/tasks/issues/562

**Comment by phet-steele** [comment]
@ariel-phet @jessegreenberg the speedometer will revert to showing 1.0 m/s every time it is made visible, even if something is moving. Try enabling the speedometer, get something moving to some speed, disable and re-enable the speedometer.

**Comment by jessegreenberg** [comment]
It looks like this was recently introduced in the refactor and merge for performance and garbage collection (ab6c09bc6ec7d5214df15706c9452afd9b2981b8).

**Comment by jessegreenberg** [comment]
We removed the callbacks to reduce the amount of garbage, but 
```js
    showSpeedProperty.link( updateReadout );
```
passes showSpeed (boolean) into updateReadout which should take a numeric value. Math.abs( true ) === 1, which is what we are seeing here.

**Comment by jessegreenberg** [comment]
Fixed in above commit.

**Comment by jessegreenberg** [comment]
@phet-steele could you please verify that this is fixed?  Here is a dev version with the change:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.2/forces-and-motion-basics_en.html

**Comment by phet-steele** [comment]
@jessegreenberg indeed it is fixed :+1:

**Comment by jessegreenberg** [comment]
Thank you @phet-steele, closing.
