### ISSUE TITLE
Pause Problem: Acceleration values don't update

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#181]
When the sim is paused and acceleration is checked, the acceleration value does not change when dynamically applying force. The values don't update until a time step.
Should be 3.3:
![accel1](https://cloud.githubusercontent.com/assets/5863899/14259275/6f45944e-fa63-11e5-9674-41036e2dfa1a.PNG)

Should be to the left:
![accel2](https://cloud.githubusercontent.com/assets/5863899/14259289/812211d8-fa63-11e5-9518-b37da9667dae.PNG)

In both of these cases, stepping the sim forward once displays the correct amount of acceleration. Note, this has an interesting side effect with the bucket. Grabbing the bucket when the water has sloshed and returning it to the grab box does not reset the image (when paused of course):
![buckaccel](https://cloud.githubusercontent.com/assets/5863899/14259393/eac2452c-fa63-11e5-8b31-44fb6d1a92a2.PNG)

Seen on all Win 10 browsers. For phetsims/tasks/issues/562.

Troubleshooting information:
Name: ‪Forces and Motion: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.1/forces-and-motion-basics_en.html
Version: 2.0.0-dev.1 2016-03-31 19:14:30 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"8774f49c","branch":"master"},"babel":{"sha":"1256d684","branch":"master"},"brand":{"sha":"4091d2e7","branch":"master"},"chipper":{"sha":"4dde25da","branch":"master"},"dot":{"sha":"da78031b","branch":"master"},"forces-and-motion-basics":{"sha":"9e3bcda6","branch":"master"},"joist":{"sha":"150c8138","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"ee35a4eb","branch":"master"},"scenery-phet":{"sha":"54df833b","branch":"master"},"sherpa":{"sha":"fc4c2c96","branch":"master"},"sun":{"sha":"77f84663","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"vibe":{"sha":"c84b3c41","branch":"master"}}

**Comment by jessegreenberg** [comment]
I would like to create a new issue for the water bucket because I have a design question about that.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, pending testing.

**Comment by jessegreenberg** [comment]
The acceleration meter and water bucket should not update when sim is paused.  See @ariel-phet's comment in https://github.com/phetsims/forces-and-motion-basics/issues/185#issuecomment-205654637

**Comment by jessegreenberg** [comment]
The Acceleration readout and water bucket node do not update until sim is playing or user hits step.  Closing.
