### ISSUE TITLE
Pause Problem: Tweakers enabled when slider is still grayed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#184]
I'm considering this a "Pause Problem" since this issue is much more obvious when the sim is paused.
@jessegreenberg this is largely a consequence of tweakers re-enabling at any point an object is not at max speed (unlike the force slider).

1. Go to the "Friction" screen.
2. Set friction to max, use the tweakers to apply max force.
3. A second after the pusher falls, pause the sim.
4. Since the pusher has fallen, the force slider will be half grayed. But since the object is not at max speed (due to friction) the tweakers are enabled. Use the tweakers to apply a force in the direction that is grayed on the slider.
5. Resume the sim (stepping may actually be better here) and the force slider will remain at 0 even though force is being applied.
![famb03](https://cloud.githubusercontent.com/assets/5863899/14261308/3e579d64-fa6d-11e5-98ab-383ee9a99149.gif)

Seen on all Win 10 browsers. For phetsims/tasks#562.

Troubleshooting information:
Name: ‪Forces and Motion: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.1/forces-and-motion-basics_en.html
Version: 2.0.0-dev.1 2016-03-31 19:14:30 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"8774f49c","branch":"master"},"babel":{"sha":"1256d684","branch":"master"},"brand":{"sha":"4091d2e7","branch":"master"},"chipper":{"sha":"4dde25da","branch":"master"},"dot":{"sha":"da78031b","branch":"master"},"forces-and-motion-basics":{"sha":"9e3bcda6","branch":"master"},"joist":{"sha":"150c8138","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"ee35a4eb","branch":"master"},"scenery-phet":{"sha":"54df833b","branch":"master"},"sherpa":{"sha":"fc4c2c96","branch":"master"},"sun":{"sha":"77f84663","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"vibe":{"sha":"c84b3c41","branch":"master"}}

**Comment by phet-steele** [comment]
Knew I'd forget to finish the title before submitting.....

**Comment by jessegreenberg** [comment]
To match the behavior of the deployed version, pressing the tweaker buttons should make the pusher stand up and the slider should update accordingly.

**Comment by jessegreenberg** [comment]
Should be fixed in the above commit.

**Comment by phet-steele** [comment]
Fixed.
