### ISSUE TITLE
When should the water bucket update?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#185]
In https://github.com/phetsims/forces-and-motion-basics/issues/181 @phet-steele pointed out that the geometry of the water bucket does not update until there is a time step, even when it is in the toolbox. The water *should* be level when it is home.

![image](https://cloud.githubusercontent.com/assets/6396244/14266955/7e223032-fa89-11e5-9aa3-5bb3cb708c59.png)

When the sim is paused, should the water geometry update when there is applied force?  Or should the water level wait to update until the user hits 'Play'?  Design question so assigning to @ariel-phet.

![image](https://cloud.githubusercontent.com/assets/6396244/14266994/c6c9393e-fa89-11e5-9419-8cc2ed926fa3.png)

**Comment by jessegreenberg** [comment]
After thinking about it, it seems that if the acceleration readout updates when the sim is paused, the water level should as well.

**Comment by jessegreenberg** [comment]
The water is now always level in the toolbox and updates when the sim is paused.  This seems like the correct behavior to match the acceleration readout and force vectors.  @ariel-phet if this is correct, please close.

**Comment by ariel-phet** [comment]
@jessegreenberg I do agree the water should always be level in the toolbox.

However, I while the sim is paused, I do not think either the water bucket OR the acceleration meter should update until you have pressed play. For instance, suppose everything is stationary, you pause the sim, and then you apply a force with the slider. You have now "set up" an experiment. There is not any acceleration until you let the force actually act. When you are paused and change the applied forces or friction in paused mode you are sort of saying "here is what I want to happen" next.

**Comment by jessegreenberg** [comment]
I see, thank you for explaining this @ariel-phet.  I will change it so that the acceleration readout and water bucket update when sim is playing (or stepped), and the water bucket will be level when home in the toolbox.

**Comment by jessegreenberg** [comment]
Should be fixed via #181.  Water bucket doesn't update water level unless sim is playing or step is pressed.  The water becomes level when the user drags the bucket.  Closing.
