### ISSUE TITLE
Levitating bucket on acceleration screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/forces-and-motion-basics#186]
Platform independent and only seems to happen the water bucket on 2.0.0-dev.2

To reproduce:
1. Go to the acceleration screen
2. put wooden crate back in tool box
3. pull out water bucket and set on the ground
4. Now lift water bucket above the position shown below and release
5. Bucket will stay hanging in the air

Note you can also do this with the bucket place on top of the crate or such, and then when you reorder objects other things get suspended, but only the bucket appears to cause this issue.

![bucket](https://cloud.githubusercontent.com/assets/4051174/14272296/1af28166-fabf-11e5-94a7-d97bf2fa7525.PNG)

![bucket 2](https://cloud.githubusercontent.com/assets/4051174/14272319/45039152-fabf-11e5-8fe9-460dfcf4b0d5.PNG)

**Comment by jessegreenberg** [comment]
Sorry about that, this was fixed in commit 7587c31fef7ed219e96e3eb4694520e6baf4776b.  Closing.
