### ISSUE TITLE
Drags aren't canceled after a reset all

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#187]
A multi-touch issue that leads to some interesting things depending on what object is being dragged while pressing the reset all button. Ignore the bad performance in the videos, it isn't the sim's fault.

1. Objects being dragged before the reset are returned to the tool box, but can then be dragged out again without the images scaling up. This causes the objects to appear smaller when placed on the stack. (When the yellow circle disappears in the video is when I use a second finger to reset the sim. My first finger dragging the box never leaves the screen.)
![famb04](https://cloud.githubusercontent.com/assets/5863899/14289566/978e3298-fb18-11e5-9e64-b4ee4cf488de.gif)

2. If the object that is being dragged before the reset happens to be the default box (the left one), then after the reset the box can be placed back in the tool box. The sim still believes the box is there, so you can both apply force to an invisible object as well as place objects higher in the stack.
![famb05](https://cloud.githubusercontent.com/assets/5863899/14289785/8d8c5300-fb19-11e5-81b5-2a627187f4ba.gif)

Recorded on Win 10 Chrome, also seen on iPad Air 2 iOS 9.3 (Leibniz). For phetsims/tasks#562.

Troubleshooting information:
Name: ‪Forces and Motion: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-dev.1/forces-and-motion-basics_en.html
Version: 2.0.0-dev.1 2016-03-31 19:14:30 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"8774f49c","branch":"master"},"babel":{"sha":"1256d684","branch":"master"},"brand":{"sha":"4091d2e7","branch":"master"},"chipper":{"sha":"4dde25da","branch":"master"},"dot":{"sha":"da78031b","branch":"master"},"forces-and-motion-basics":{"sha":"9e3bcda6","branch":"master"},"joist":{"sha":"150c8138","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"ee35a4eb","branch":"master"},"scenery-phet":{"sha":"54df833b","branch":"master"},"sherpa":{"sha":"fc4c2c96","branch":"master"},"sun":{"sha":"77f84663","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"vibe":{"sha":"c84b3c41","branch":"master"}}

**Comment by phet-steele** [comment]
@jessegreenberg from phetsims/scenery/issues/218 I'm guessing this should be deferred?

**Comment by jessegreenberg** [comment]
In this case, we might be able to handle this sim-side until https://github.com/phetsims/scenery/issues/218 is addressed.  I will take a quick look before deferring.

**Comment by jessegreenberg** [comment]
Also an issue for the Net Force screen.

**Comment by jessegreenberg** [comment]
Should be fixed, marking as fixed-pending-testing.

**Comment by phet-steele** [comment]
@jessegreenberg the current fix still leads to the sim being quite broken.
1. Go to the Friction screen.
2. Grab the default box with one finger, reset the sim with the other.
3. While still holding the box in place, use another finger to hold down a tweaker (for maybe 3 secs).
4. Place the box back into place (not the toolbox).

Video capture rate isn't fast enough (so try it yourself), but once max speed is reached the pusher flickers between fallen and upright and occasionally leads to https://github.com/phetsims/forces-and-motion-basics/issues/180#issuecomment-212528012
![famb08](https://cloud.githubusercontent.com/assets/5863899/14684863/1f76f8ca-06ef-11e6-8063-533064179e8d.gif)

**Comment by phet-steele** [comment]
Commit fixed it, thanks @jessegreenberg. There's other multitouch problems that having nothing to do with dragging and resetting, so closing this.
