### ISSUE TITLE
iPad performance

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#190]
The iPad Air 2 named Leibniz (our beefiest tablet) has a very noticeable ,presumably, garbage collection every 30 seconds. You can see this easily on any motion screen. Set friction to 0 and let an object travel at max speed. Eventually you'll see the performance drop, maybe wait a few minutes.

This is seen on master (4/21), not in 2.0.0-dev.2.

**Comment by jessegreenberg** [comment]
I am not able to observe any stuttering on master on my machine, but I am about to test on an iPad2.  On master, he heap was stable at 25.5 MB through about five minutes of snapshots.  The JS Heap on the timeline does not indicate any kind of memory leak.  

About to try on my iPad2 to reproduce on master for requireJS and a built version.

**Comment by jessegreenberg** [comment]
I just ran 2.0.0-dev.1 and 2.0.0-dev.2 for about ~10 minutes each on the iPad2 and verified that this cannot be reproduced for those versions.

**Comment by jessegreenberg** [comment]
RequireJS version of master ran on iPad2 iOS 9.3.1 for 10 minutes and there was no noticeable change in performance.

**Comment by jessegreenberg** [comment]
Built version of master ran on iPad2 iOS 9.3.1 for 10 minutes and there was no noticeable change in performance, and I could not see a stutter for garbage collection.  I think that we are good to proceed with the RC, and as part of RC testing we should make sure that this issue cannot be reproduced on Leibniz or any other tablet.

**Comment by phet-steele** [comment]
Leibniz has been running fine for awhile now with only slight stuttering. Definitely not as bad as on 4/21, maybe Leibniz was just having a bad day. Tycho testing will be up next.

**Comment by phet-steele** [comment]
Tycho also fine.
