### ISSUE TITLE
Precision of friction force causes bad physics

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#197]
@samreid @ariel-phet Revealed through PhET-iO, and similar to phetsims/energy-skate-park-basics/issues/355, there is a precision issue outlined by the screenshots below.

This setup appears to show friction equaling applied force:
<img width="240" alt="screen shot 2016-09-08 at 11 47 24 am" src="https://cloud.githubusercontent.com/assets/5863899/18360147/14ec894e-75ba-11e6-84cb-f869a183f925.png">

But in reality the absolute value of friction force is greater than the applied force (applied force is exactly 50N):

<img width="613" alt="screen shot 2016-09-08 at 11 47 28 am" src="https://cloud.githubusercontent.com/assets/5863899/18360152/1862b706-75ba-11e6-86df-7ff7edf6725a.png">

With this setup, and the speedometer shown, the moving object DOES slow down. Certainly a problem if the net force on the object appears to be 0.

**Comment by samreid** [comment]
@ariel-phet suggests rounding the applied force and friction force to the nearest 1, so the display values will match the model values.

Speed will still be shown as a decimal.

@ariel-phet says priority should be relatively high.

@jessegreenberg says he could work on it.

Thanks @jessegreenberg, let me know if you need help.

**Comment by oliver-phet** [comment]
Also assigning myself to communicate with user when things are fixed!

**Comment by samreid** [comment]
Discretizing the applied force slider is a good idea.  Discretizing the friction slider will not work (because the friction force is computed based on it and other factors), and the friction force may need to be discretized in the model.

**Comment by jessegreenberg** [comment]
@samreid yes, that is true.  The above commit handles this as described in https://github.com/phetsims/forces-and-motion-basics/issues/197#issuecomment-245725596.  The applied force is rounded by the slider while the friction force is rounded after calculation in the model.  The result is that the forces in the model are equal to what is shown in the view.  I verified in an instance proxy.

In the maintenance release for this issue, we may also want to include #198.

**Comment by phet-steele** [comment]
This looks good, I let the sim run for ~10 mins with equivalent applied and friction forces and saw no change in speed. @oliver-phet this will be fixed when the sim is released. Keeping his open until then.

**Comment by phet-steele** [comment]
@oliver-phet, sim is deployed.

**Comment by oliver-phet** [comment]
User has been notified, closing!
