### ISSUE TITLE
Standardize main pattern

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#200]
@andrewadare pointed out that FAMB main is a bit odd.  Let's standardize it.  Tagging @jessegreenberg in case he is in the neighborhood.

**Comment by samreid** [comment]
Fixed above, @jessegreenberg can you please pull and make sure everything's ok?

**Comment by jessegreenberg** [comment]
This looks great, thanks @andrewadare and @samreid.  Everything is working great.
