### ISSUE TITLE
StringTest=double overlap

### ISSUE THREAD

**Issue by BryceAG** [phetsims/forces-and-motion-basics#202]
Test device:
Bates

Operating System:
Win 7, Win 10

Browser:
Chrome, Firefox, IE, Edge

Problem description:
with stringTest=double or long, the buttons for changing the force for motion, friction, and acceleration sections are overlapped by the item selection boxes

Steps to reproduce:
use stringTest=double or long, go to any section other than net force.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/19251747/23328bf4-8efe-11e6-8e96-3b826a43c5e5.png)

Troubleshooting information (do not edit):
Name: ‪Forces and Motion: Basics‬:‪Forces and Motion: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.3/forces-and-motion-basics_en.html?stringTest=double
Version: 2.1.0-rc.3 2016-10-06 22:01:12 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"740673a2","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"4d36bb54","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

related to phetsims/tasks#697

**Comment by jessegreenberg** [comment]
Thanks very much @BryceAG, fixed in above commits for both 2.1 and master.  Closing.

**Comment by jessegreenberg** [comment]
(verification)

![capture](https://cloud.githubusercontent.com/assets/6396244/19253524/ec9fbc64-8f08-11e6-96b9-096ea8a59020.PNG)
