### ISSUE TITLE
Build failing with phetio in version name

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#204]
@zepumph, the commit c5906c1869b6b1635fb069c6488afabf0a817fed causes the sim to fail to build (see  phetsims/chipper/issues/507).

@zepumph @samreid can we revert this commit for now? Or is it important for the time being?

**Comment by samreid** [comment]
@zepumph committed a fix, please pull and proceed.

**Comment by phet-steele** [comment]
@zepumph, good to go!
