### ISSUE TITLE
?stringTest=x layout problems

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#205]
`?stringTest=x` causes overlap on the Net Force screen:
<img width="126" alt="screen shot 2016-10-11 at 2 18 15 pm" src="https://cloud.githubusercontent.com/assets/5863899/19287110/a6fb3368-8fbd-11e6-92ce-a718640f9a0d.png">

With a similar cramped feeling on the Motion screen. I'm assuming these buttons are simply aligned to the left edge of the panel and move accordingly when the panel width decreases.
<img width="221" alt="screen shot 2016-10-11 at 2 29 45 pm" src="https://cloud.githubusercontent.com/assets/5863899/19287550/5498bada-8fbf-11e6-9210-fdd66ac60dd9.png">

Seen on macOS 10.12 browsers. For phetsims/tasks/issues/697.
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.3/forces-and-motion-basics_en.html
Version: 2.1.0-rc.3 2016-10-06 22:01:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"740673a2","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"4d36bb54","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, added a bit of separation between the buttons, *only* when the buttons are too close together.

![separation1](https://cloud.githubusercontent.com/assets/6396244/19907030/ca8e6bca-a042-11e6-8f6e-5e52a1301643.PNG)

![separation2](https://cloud.githubusercontent.com/assets/6396244/19907032/cc48b9d4-a042-11e6-95a1-33338bc294df.PNG)
