### ISSUE TITLE
Right facing image is offset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#207]
The people's right facing image is not centered around the mass label when being dragged. The mass label is in the correct position, I believe:

<img width="163" alt="screen shot 2016-10-17 at 11 29 48 am" src="https://cloud.githubusercontent.com/assets/5863899/19448046/4d4d860a-945d-11e6-9cd3-53fa01b95dd9.png">
<img width="181" alt="screen shot 2016-10-17 at 11 30 07 am" src="https://cloud.githubusercontent.com/assets/5863899/19448052/51dc6c4a-945d-11e6-94c9-4682c2936018.png">

Seen on macOS 10.12 browsers. For phetsims/tasks#697.
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.3/forces-and-motion-basics_en.html
Version: 2.1.0-rc.3 2016-10-06 22:01:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"740673a2","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"4d36bb54","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
@phet-steele do you know if this is a new bug or is this in the deployed version as well?

**Comment by phet-steele** [comment]
> do you know if this is a new bug or is this in the deployed version as well?

Not a new issue

**Comment by jessegreenberg** [comment]
This is caused by this line:
```js
        //NOTE: I'm not sure why there is an extra 20 pixels in this direction, but it seems necessary to center the images
        normalImageNode.scale( -1, 1 );

        var imageWidth = normalImageNode.width * item.getCurrentScale();
        normalImageNode.translate( -imageWidth - 20, 0 );
```

It seems like we should be able to apply the 20px offset to the mass label, but it would be best to figure out why the offset is necessary.

**Comment by jessegreenberg** [comment]
Should be fixed in the commit above.

**Comment by phet-steele** [comment]
@jessegreenberg If the girl is returned to the tool box while facing right, her image turns to face left but the mass label does not adjust:

![famb02](https://cloud.githubusercontent.com/assets/5863899/20024112/0b5ce424-a2aa-11e6-9ede-59d99ecd7359.gif)

**Comment by phet-steele** [comment]
Fixed, thanks @jessegreenberg.
