### ISSUE TITLE
Pushing on people's fronts

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#208]
Present in the deployed version:
1. Screen 2,3, or 4. Disable friction (if applicable).
2. Place a person on the stack, with at least one other object below them and not the other person above them.
3. Apply force toward the right and get the stack moving at an appreciable rate.
4. Start applying force toward the left.
5. While the stack is still moving to the right, pick up the person and place them back on the stack. Now, even though force is being applied toward the left, the person on the stack is facing right.

![famb01](https://cloud.githubusercontent.com/assets/5863899/19450302/1f2e2726-9466-11e6-9c03-764ea7caeafd.gif)

Seen on macOS 10.12 browsers. For phetsims/tasks#697.
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.0-rc.3/forces-and-motion-basics_en.html
Version: 2.1.0-rc.3 2016-10-06 22:01:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"740673a2","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"4d36bb54","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Should be fixed in the above commit, to be verified in the next RC test.

**Comment by phet-steele** [comment]
I haven't found a way to reproduce this anymore, thanks @jessegreenberg.
