### ISSUE TITLE
Modify teacher tips: add general statement about "magical" pusher.

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#209]
On 10/31 Ariel wrote:
> The sim assumes the "dummy" -- what we refer to as the "pusher" -- is able to apply a force without needing friction from the ground on its feet. For instance the pusher could have something like a rocket power or such that does not require pushing against the ground. It is a bit on the "magical" side, but there are plenty of ways you could imagine having such a pusher be powered (with a rocket, a jet pack, a electromagnetic system on the road). We more wanted a clear physical object to be pushing on the masses and clearly represent the applied force.
> 
> We might consider adding something to the teacher tips (this simplification is noted in the tips for the net force screen but not for the motion screens).
> 
just ask Amy R for a slight modification. Maybe just a more general statement, since right now in the tips the "magical" sense of the pusher/pullers is noted for the Net force screen, but it is an overall model simplification.

@arouinfar Can you add a statement to the tips to address this?

**Comment by arouinfar** [comment]
@oliver-phet can do, but I'm going to wait until the next version of the sim is published, since #199  also requires the Teacher Tips to be modified.

**Comment by oliver-phet** [comment]
Sounds great, thanks!

**Comment by arouinfar** [comment]
I've added this statement to the Teacher Tips, and will upload once the sim is redeployed.

>The pullers and pushers are used to embody the applied force, but are somewhat “magical” as they don’t require friction between the ground and their feet to apply a force. One could also imagine the pullers and pushers being propelled in a way does not require pushing against the ground, such as rocket power or by an electromagnetic rail in the ground (like a maglev train).

**Comment by jessegreenberg** [comment]
@arouinfar 2.1.0 has been redeployed, removing the on-hold label.

**Comment by arouinfar** [comment]
Excellent! I'll get it uploaded this afternoon.

**Comment by arouinfar** [comment]
Uploaded!
