### ISSUE TITLE
User suggestion: max newtons to 1000 or 2000N

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#211]
> Problem description: It’s not really a problem, it is more a needed addition. I feel that you guys/gals should add more increments to your program. So instead of the max increment for Newtons being 500 it should be 1000 or 2000N. The same for the weight/mass.

**Comment by ariel-phet** [comment]
@oliver-phet let the user know we will consider this for the full version of forces and motion, but for the basics version the max value of applied force was specifically chosen to mesh well with the lowest mass to produce an acceleration that performs wel and accuratelyl on all platforms.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing for now.
