### ISSUE TITLE
Slider thumb affecting panel max width

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#212]
The panels on the Friction and Acceleration screen have this issue when using `?stringTest=x`: phetsims/rutherford-scattering/issues/97.

For phetsims/tasks/issues/721.

**Comment by jessegreenberg** [comment]
The title of teh slider is also moving around with this string test.

**Comment by jessegreenberg** [comment]
resize: false flags in the panel and the VBox holding the slider and label should fix this.

**Comment by phet-steele** [comment]
Fixed, thanks @jessegreenberg.
