### ISSUE TITLE
User suggestion: add hundredths digit to acceleration value

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#217]
A suggestion--For the simulation "Forces and Motion: Basics" with acceleration tab, give values with more digits--at least 2 significant digits. 
When my students ran the program to see relationship between mass, force and acceleration they get the same values when not the same input values are used. For example, when keeping force at 50 N (no friction) they get 0.3 m/s2 when they use masses of 150 kg and 200 kg.
I hope you can fix this before next semester. 
Also, we used the chrome version.
Thanks.

**Comment by ariel-phet** [comment]
@arouinfar this seems like a reasonable change. I suppose my only question is do we display hundredths only in the case where we have something like 0.XX m/s^2 (so there are 2 sig figs always) and go to just tenths when it is some number like XX.X m/s^2, or do we always display the second decimal point?

@jessegreenberg I assume displaying the hundredths place would overall be a trivial change?

**Comment by arouinfar** [comment]
Seems reasonable to me too @ariel-phet. In general, I'd prefer to keep a consistent number of decimal places rather than a consistent number of digits. I'll take a look at FAMB to see which option is more appropriate in this context.

**Comment by arouinfar** [comment]
@ariel-phet I took a look at FAMB, and I'm still leaning towards always displaying the hundredths place. I think it would feel strange to lose a decimal place at high (>10 m/s^2) values of acceleration.

**Comment by ariel-phet** [comment]
Sounds good to me @arouinfar.

@jessegreenberg perhaps make this change in a way we can test? Either on phettest or such?

**Comment by jessegreenberg** [comment]
@ariel-phet @arouinfar can you review this version?

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.1-rc.2/forces-and-motion-basics_en.html

This includes changes for #213.

**Comment by arouinfar** [comment]
Looks good to me! Thanks @jessegreenberg.

**Comment by ariel-phet** [comment]
Looks good to me as well!

**Comment by jessegreenberg** [comment]
Great, thanks.  We will bring in a change for #218 before redeploying.

**Comment by jessegreenberg** [comment]
This maintenance release should include changes for

- [ ] #218 
- [ ] #217
- [ ] #214
- [ ] #213

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.1-rc.3/forces-and-motion-basics_en.html

Just goint to sanity check for a few minutes before redeploying.

**Comment by jessegreenberg** [comment]
@arouinfar @ariel-phet @oliver-phet version 2.1.1 has been deployed with changes for #218, #217 and #213.

Assigning back to @oliver-phet in case the user should be notified.

**Comment by oliver-phet** [comment]
User emailed. Closing.
