### ISSUE TITLE
Should meter icons dynamically update?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/forces-and-motion-basics#218]
While reviewing #217, I noticed that the speed and acceleration meter icons next to the checkboxes dynamically update. This behavior differs from ESPB, where the speedometer icon is a static image. 

At rest:
<img width="228" alt="screen shot 2016-11-30 at 12 12 23 pm" src="https://cloud.githubusercontent.com/assets/8419308/20767150/4c01f5b8-b6f6-11e6-85a5-b9ce1c407a32.png">

While in motion:
<img width="230" alt="screen shot 2016-11-30 at 12 12 33 pm" src="https://cloud.githubusercontent.com/assets/8419308/20767152/4c04dad0-b6f6-11e6-9b7d-e52ca5a5567d.png">

@jessegreenberg has confirmed that this behavior dates back to FAMB 1.0.0. Frankly, I find it a bit odd, and I think that it has the potential to interfere with predictive questions.

@ariel-phet do you remember a discussion about this particular behavior? Was it intentional? If not, is this something we can/should address in the upcoming redeploy?

**Comment by ariel-phet** [comment]
@arouinfar this was intentional. 

@samreid basically did this at the time because he thought it looked cool and the team agreed (it was sort of a bell and whistle at the time). However, I don't think the idea of interfering with predictive questions was considered.

It seems a static image has become more of our standard, so I think it would be fine to make it static. I would say for acceleration use an image that shows some level of acceleration present on the meter. I think the speedometer is iconic enough that it does not matter whether the speed in the icon is zero or some nominal speed.

**Comment by ariel-phet** [comment]
@arouinfar I agree certainly seems like an easy tweak to make for the next deploy/maintenance release.

**Comment by arouinfar** [comment]
Thanks @ariel-phet!

>he thought it looked cool and the team agreed

My initial reaction was along the lines of "wow, that's cool!" so I can see how the behavior made it into the sim. :)

> I would say for acceleration use an image that shows some level of acceleration present on the meter. 

I think ~5 m/s^2 looks pretty good
<img width="229" alt="screen shot 2016-11-30 at 1 02 09 pm" src="https://cloud.githubusercontent.com/assets/8419308/20769007/6933dc80-b6fd-11e6-8761-c58fc0144892.png">

>  I think the speedometer is iconic enough that it does not matter whether the speed in the icon is zero or some nominal speed.

Agreed. For consistency with ESPB, I would leave the needle at zero.

**Comment by jessegreenberg** [comment]
@arouinfar @ariel-phet here is the latest with this change:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.1-rc.3/forces-and-motion-basics_en.html

Are we ready to redeploy this maintenance release?

**Comment by arouinfar** [comment]
Looks good! I think everything's ready for the redeploy @jessegreenberg, but @ariel-phet can confirm.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, I think we are ready to go.  Closing this issue and I will track the maintenance release in #217.
