### ISSUE TITLE
User request: speedometer to Net Force, disable "Red/Blue Wins"

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#220]
> I'm writing about a feature request in the force basics tug of war html5 sim. I use it on day 2 of my forces unit to make a connection between balanced/unbalanced force and constant/changing motion.
> 
> Two requests are:
> Can there be a speedometer option in the tug of war? Students argue about whether the cart reaches a constant speed when one guy is pulling, and it's hard to isolate the evidence to suggest that the cart keeps changing motion.
> 
> Any way to turn off the "Red/Blue Wins" outcome, and just see the cart move off screen? Students point to the stopped cart as evidence that the cart has slowed down (with no one pulling) and I end up having to repeat over and over that the simulations stops being useful when one team wins.

**Comment by ariel-phet** [comment]
@arouinfar I know we keep refining this sim....but these are interesting suggestions on the first screen. The more on chew on this it seems like having some way to indicate acceleration or constant speed seems valuable. A speedometer seems fairly natural, but on this screen if we had one it would definitely need to be qualitative since we have no masses listed. 

I also do not think it would be a huge deal to have the blue/red wins come up but have the cart continue to move (they can always press the return button). 

Thoughts? If you agree, we should consider mocking something up.

**Comment by oliver-phet** [comment]
Additional email from user:

> I've attached the main document I use with students on the Tug of War rollout - though we come back to it again and again... 
> 
> This handout is written to correspond to Eugenia Etkina's ISLE cycle - we're using the tug of war to perform observation experiments, look for patterns, then to test specific ideas by making predictions.
> 
[BFM_2TugOfWarPDF.pdf](https://github.com/phetsims/forces-and-motion-basics/files/839079/BFM_2TugOfWarPDF.pdf)

**Comment by arouinfar** [comment]
@ariel-phet I think the user makes a really good point. I don't see the "Red/Blue Wins" banner as the culprit, however. I think allowing pullers to continue off-screen would be sufficient to address the user's request. I can also see how a qualitative speedometer would be a very useful tool here. I'll go ahead and create some mockups.

**Comment by arouinfar** [comment]
Screens 2-4 have the speedometer located at the exact same place in the play area. This positioning won't work on the first screen, as there will be some overlap with the Sum of Forces vector.
![screen shot 2017-03-13 at 4 11 10 pm](https://cloud.githubusercontent.com/assets/8419308/23877396/c1df64c0-0807-11e7-9591-ebd1b4910c34.png)

Scaling the speedometer down to 75% (keeping top-center position the same) will allow the speedometer to clear the Sum of Forces vector.
![screen shot 2017-03-13 at 4 11 21 pm](https://cloud.githubusercontent.com/assets/8419308/23877395/c1df1cc2-0807-11e7-8dcf-ba28a69ab17c.png)

Scaling the speedometer down 70% provides a bit more negative space. This looks about right to me. Thoughts @ariel-phet?
![screen shot 2017-03-13 at 4 11 29 pm](https://cloud.githubusercontent.com/assets/8419308/23877397/c1e66b1c-0807-11e7-990e-81d59c25854f.png)

**Comment by arouinfar** [comment]
A few more thoughts:
* The mockups display the instant where the "Blue Wins" flag would appear. The cart would continue moving to the left, rather than stopping. 
* I've pasted the max length Sum of Forces vectors into the last two mockups to see how the Speedometer would look when there's a large net force.
* The Sum of Forces arrowhead will still come pretty close to the Speedometer, so it should probably be moved down ~10 px.


Updated mockup with Sum of Forces moved down 10px and Speedometer scaled to 70%: 
![image](https://cloud.githubusercontent.com/assets/8419308/23877810/c275a532-0809-11e7-9b76-02d011a41654.png)

**Comment by ariel-phet** [comment]
@arouinfar a few thoughts...

My first instinct would be to put the speedometer centered top. I feel like centering the speedometer is important (this is just my instinct) to feel like it is measuring the speed of the whole system. I know that seems obvious, but biasing it to one side feels odd. It seems the "Sum of Forces" label and arrow can move down a bit. Perhaps the flag could appear in the upper left of the sim? Or on the cart?

Another whacky idea would be to put the speedometer on the cart itself (it moves pretty slowly even at max acceleration) and we don't do the whole "ground moving to cause the illusion of movement" here, so I think that could also work . Students are likely focused on what the cart is doing anyhow, and it might be a convenient representation to just plop on it.

**Comment by arouinfar** [comment]
Thanks for the suggestions @ariel-phet. I think having the speedometer centered would be a nice touch, though I'm not sure I agree that it's necessary.

Moving the speedometer onto the cart itself or centering it at the top of the screen requires the speedometer to be quite a bit smaller -- 55% of its current size. However, I think the speedometer still seems big enough. I wouldn't make it any smaller, though.

Placing the speedometer on the cart doesn't actually feel too whacky!
![image](https://cloud.githubusercontent.com/assets/8419308/23878956/f5607610-080f-11e7-9da3-1a63ff56748f.png)

Centering the speedometer at the top of the screen causes some awkwardness with the flag, however. I think placing the flag onto the cart is the most reasonable option.
![image](https://cloud.githubusercontent.com/assets/8419308/23879014/379d0624-0810-11e7-90f7-9e41f6b6b9e8.png)

Placing the flag on the top left looks a bit strange if the speedometer is off or if Red wins.
![image](https://cloud.githubusercontent.com/assets/8419308/23879055/7cbee20e-0810-11e7-8a74-fcaedca14659.png)
![image](https://cloud.githubusercontent.com/assets/8419308/23879063/85f89ed2-0810-11e7-97a4-f15290e64dbd.png)
![image](https://cloud.githubusercontent.com/assets/8419308/23879071/8e50c1e0-0810-11e7-8264-e614abd9860f.png)

We could also keep the flags a bit closer to the center and show it to the left or right of the speedometer, depending on the winner. I think this option is a bit worse than keeping the flag to the left.
![image](https://cloud.githubusercontent.com/assets/8419308/23879322/eaf10512-0811-11e7-8c36-44ba6f5f0a26.png)
![screen shot 2017-03-13 at 5 25 01 pm](https://cloud.githubusercontent.com/assets/8419308/23879350/1340d47a-0812-11e7-9ec5-9a33d4e848af.png)



We could also obscure the pullers with the flag. At that point, the tug-of-war is technically over, so I don't find it particularly bothersome to obscure the pullers. Turning off the speedometer doesn't make the flag seem off-balance, either.
![image](https://cloud.githubusercontent.com/assets/8419308/23879007/2d74a9a4-0810-11e7-905a-67f20b5cfca4.png)
![image](https://cloud.githubusercontent.com/assets/8419308/23879112/c312a8c6-0810-11e7-9fd6-3648654e4d47.png)

Back to you @ariel-phet.

**Comment by jessegreenberg** [comment]
@arouinfar is the speedometer value readout large enough when scaled down to that size?

**Comment by arouinfar** [comment]
@jessegreenberg the speedometer would just be qualitative, so there wouldn't be a value. I think the needle would still be readable at that size. Do you have any other thoughts about the layout changes?

**Comment by ariel-phet** [comment]
@arouinfar I am kind of liking the speedometer on the cart

1. One problem with putting the red/blue wins flag over the pullers is you would still be able to interact with the pullers

2. Part of me would also be OK with removing the "wins" flag altogether. We no longer call this screen "tug of war" and it is sort of obvious which side "wins". If we let the cart continue to go off screen, we could get some weirdness with the "wins" flag...for instance lets say you just have a blue puller on a press go...The "Blue Wins!" flag comes up but the cart is still moving and then you decide to load red pullers on, and get it going the other way. It could become confusing.

**Comment by arouinfar** [comment]
> @arouinfar I am kind of liking the speedometer on the cart

Agreed. If we decide to re-locate the speedometer on the first screen, I think the cart is the best place.

> One problem with putting the red/blue wins flag over the pullers is you would still be able to interact with the pullers

Very true. This would require the users to return the cart before setting up a new experiment, which I hadn't thought about. 

> Part of me would also be OK with removing the "wins" flag altogether.

Me too, actually, but I think removing it could get complicated. I wonder what implications this would have for the wrappers we've built for FAMB. I'm pretty sure the wrapper AH worked on used a screenshot of the flag in the data table.

> The "Blue Wins!" flag comes up but the cart is still moving and then you decide to load red pullers on, and get it going the other way.

Could the flag disappear if more pullers are added on and the direction of the net force changes? Say blue wins, but more red pullers are added to tip the net force towards red. The flag would disappear until a blue puller reaches the midpoint of the screen.

**Comment by ariel-phet** [comment]
@arouinfar I kind of like the flag disappearing if more interaction occurs that could change the result, that will require adding some logic. 

@jessegreenberg thoughts on the difficulty of that sort of logic/interaction?

**Comment by jessegreenberg** [comment]
@ariel-phet @arouinfar it would be very straight forward to implement that kind of thing.

**Comment by jessegreenberg** [comment]
@arouinfar @ariel-phet something like this:
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.7-no-end-game.3/forces-and-motion-basics_en.html

We probably would want to stop disabling the "Pause" button.

**Comment by jessegreenberg** [comment]
Ah, I think I misunderstood - in the above version, the team needs to have the largest force to win. But we want the game to continue when a puller is added/removed correct? So it should be possible for the blue team to win even if there is more force from the read team.

**Comment by jessegreenberg** [comment]
Ok, something like this:
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.7-no-end-game.4/forces-and-motion-basics_en.html

This doesn't include layout changes.

**Comment by ariel-phet** [comment]
@jessegreenberg that looks good! Would it be a ton of work to slap a speedometer on the cart? If not too much work it would be great to make a dev version and then discuss with Kathy

**Comment by jessegreenberg** [comment]
It should be pretty simple to add the speedometer.

**Comment by jessegreenberg** [comment]
Here is a version with the speedometer added (with the panel checkbox):
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.7-no-end-game.6/forces-and-motion-basics_en.html

**Comment by jessegreenberg** [comment]
scenery-phet's ```GaugeNode``` wasn't intended to be this small, it doesn't support changing size off the label text and the ticks, I will take a look at that.

**Comment by jessegreenberg** [comment]
I also like 3, that seems most clear and handles the issue brought up in this user request.

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar I think the cart stopping at the edge of the screen would be fine, and I think I am liking the speedometer on the cart, it seems to work quite well, especially when the cart is in motion, accelerating, and you add another puller to balance the forces (so a constant speed is achieved) - it is immediately obvious.

**Comment by jessegreenberg** [comment]
@arouinfar can you please provide a mock up that shows what the barrier should look like?

**Comment by arouinfar** [comment]
@jessegreenberg @ariel-phet I've mocked up a few options, but they all feel pretty heavy, save for this one:

![screen shot 2017-03-23 at 11 43 09 am](https://cloud.githubusercontent.com/assets/8419308/24261846/f63b8f92-0fbd-11e7-8826-b605f19d4dd2.png)

The stopper doesn't look too obtrusive. The pullers would pass it with ease (and should be layered above the stopper).
![screen shot 2017-03-23 at 11 43 58 am](https://cloud.githubusercontent.com/assets/8419308/24261873/09a5a310-0fbe-11e7-8fe7-7764d48b3cec.png)
![screen shot 2017-03-23 at 11 44 23 am](https://cloud.githubusercontent.com/assets/8419308/24261888/170d9a26-0fbe-11e7-9f02-88db1ba2b427.png)

Here are a few other options, in decreasing order of my preference
![screen shot 2017-03-23 at 11 46 36 am](https://cloud.githubusercontent.com/assets/8419308/24262019/65fc2f8a-0fbe-11e7-89d4-43e96c26cab4.png)
![screen shot 2017-03-23 at 11 46 13 am](https://cloud.githubusercontent.com/assets/8419308/24262020/65fc4902-0fbe-11e7-997d-03d9763faf9f.png)
![screen shot 2017-03-23 at 11 46 20 am](https://cloud.githubusercontent.com/assets/8419308/24262018/65fadaea-0fbe-11e7-94fb-51916c1f60de.png)

**Comment by kathy-phet** [comment]
I like this one, but would suggest making the stopper a steel grey, like metal. 
![image](https://cloud.githubusercontent.com/assets/5096804/24264714/e34956fe-0fc6-11e7-8c48-fd848884e0bb.png)

**Comment by kathy-phet** [comment]
I'd like to keep the blue/red "wins" flag. Is that the plan?

**Comment by arouinfar** [comment]
Something like this @kathy-phet?
![screen shot 2017-03-23 at 1 58 57 pm](https://cloud.githubusercontent.com/assets/8419308/24267779/0bc11220-0fd1-11e7-9f24-98f0b08ebeec.png)

**Comment by arouinfar** [comment]
And, yes, we'll be keeping the flag.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/forces-and-motion-basics/issues/220#issuecomment-288842615

That looks good to me @arouinfar! Are the grey "stoppers" at the edge of the dev bounds? Currently the game is over when the cart gets to about half way from center to dev bounds.

**Comment by ariel-phet** [comment]
@arouinfar @jessegreenberg that looks good (I think we would want to layer the pullers above the stoppers)

**Comment by arouinfar** [comment]
> Are the grey "stoppers" at the edge of the dev bounds?

@jessegreenberg I have placed the outer edge of the stopper at the dev boundary, which would roughly place the edge of the cart at the dev boundary.


>  (I think we would want to layer the pullers above the stoppers)

Agreed @ariel-phet!

**Comment by kathy-phet** [comment]
Looks good to me!

Sent from my iPhone

On Mar 23, 2017, at 4:37 PM, Amy Rouinfar <notifications@github.com<mailto:notifications@github.com>> wrote:


Are the grey "stoppers" at the edge of the dev bounds?

@jessegreenberg<https://github.com/jessegreenberg> I have placed the outer edge of the stopper at the dev boundary, which would roughly place the edge of the cart at the dev boundary.

(I think we would want to layer the pullers above the stoppers)

Agreed @ariel-phet<https://github.com/ariel-phet>!

**Comment by jessegreenberg** [comment]
Sorry, no, but this should be pretty quick, I will work on it today.

**Comment by jessegreenberg** [comment]
@ariel-phet @arouinfar @kathy-phet here is a version with these changes:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.7-dev.4/forces-and-motion-basics_en.html

What do you think?

**Comment by ariel-phet** [comment]
I think that is all looking quite nice, working quite well @jessegreenberg!

To me, now there remains one issue...when the race is finished we may need to stop showing the force arrows. When the cart hits the "hard-stop" and one of the flags appears declaring the winner, the stop is actually providing a force. So it might be easiest to just hide all forces once the cart hits the stop. Or perhaps we have all the pullers "stand up" when the cart hits the stop. I think hiding forces would be the easiest because then we avoid sticky questions about the net force applied to instantaneously stop the cart etc.

Thoughts @arouinfar and @kathy-phet?

**Comment by arouinfar** [comment]
@jessegreenberg I like the stoppers quite a bit! I completely agree with @ariel-phet in regards to the force vectors -- we shouldn't continue to show them once the cart stops. 

At minimum, the vectors should be hidden. I do really like @ariel-phet's suggestion for the pullers to "stand up" (like they do before Go is pressed) once the cart stops, but I don't know how feasible it would be.
![image](https://cloud.githubusercontent.com/assets/8419308/25353355/33b9f3c6-28ec-11e7-8e73-206188856765.png)

**Comment by jessegreenberg** [comment]
Making the pullers stand up at the end of the game is a trivial change, here it is in a dev version:

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.7-dev.5/forces-and-motion-basics_en.html

Reassigning to @arouinfar and @ariel-phet.

**Comment by ariel-phet** [comment]
@jessegreenberg I think that looks good/works well. Probably we also want to hide the force vectors when everything stops (since the pullers stand up now). So then we should have all vectors hide once the "round" of pulling is over.

**Comment by jessegreenberg** [comment]
@ariel-phet just to clarify, the force vectors are visible while the pullers are standing before pressing "Go!", so why should they be invisible when the game ends? A dotted stroke around the arrows already indicates that the forces are not active on the cart, and is used to represent this while pulling is paused and before pulling starts.

**Comment by ariel-phet** [comment]
@jessegreenberg good point! I am little fuzzy today, and I don't think I was paying much attention to the beginning. That does seem consistent.

**Comment by ariel-phet** [comment]
@jessegreenberg I think it would be good to have @kathy-phet take a look before we publish. Can you plan to bring up at the next status meeting (2 weeks I believe)

**Comment by jessegreenberg** [comment]
Wil do.

**Comment by jessegreenberg** [comment]
We discussed this in status meeting 11/4/17.  @kathy-phet and the team approved of the changes, but @kathy-phet said she wanted to play with the latest version before proceeding with the redeploy.  @jessegreenberg sent it to her in an email.

**Comment by kathy-phet** [comment]
Looks great to me. 

@samreid - Seems like it should be decided as to whether to update the PhET-iO version with these changes. I would vote yes -- as they are nice improvements.

**Comment by arouinfar** [comment]
@kathy-phet if @samreid updates the PhET-iO version, we may want to consider what effect it would have on the wrapper @amyh-phet worked on.

**Comment by kathy-phet** [comment]
The wrapper points to a static version, so it would be OK. It would be for our current clients like BrainPop use.

**Comment by samreid** [comment]
It seems good to get in the pattern of testing/republishing PhET-iO versions when the PhET versions change. @jessegreenberg is this something you can do?  I forget how familiar you are with the instrumentation process (I recall we started on a sim together, but I think we got distracted).

**Comment by jessegreenberg** [comment]
> (I recall we started on a sim together, but I think we got distracted)

Thats how I remember it too :)  I am happy to look into this, but I would need some documentation to learn where to start.  I will defer to your judgement on whether or not this is a good place for me to continue learning about PhET-iO.

**Comment by samreid** [comment]
While I generally agree with the comment in https://github.com/phetsims/forces-and-motion-basics/issues/220#issuecomment-299348273 the QA team is very busy with other tasks, so we should coordinate with @ariel-phet and perhaps consult with @kathy-phet about the priority of re-instrumenting/re-testing/re-releasing the PhET-iO version with these new features.

**Comment by jessegreenberg** [comment]
We discussed this 6/1/17 status meeting:
@ariel-phet said that there isn't a particular rush for publishing this features.  Ideally they would be published before the end of the school year.

@zepumph will work on publishing this with updates to PhET-iO features when he returns to work. @samreid suggested that it would be helpful to have a list of new features associated with this issue so it is easier to  instrument.

- All changes are in the "Net Force" screen
- NetForceScreenView includes two new ```CartStopperNodes``` placed t a location which will stop movement of the carts.
- The cart can move about twice as far along the screen since the stoppers are placed farther than the previous version allowed the cart to move.
- The pullers stand up when the game is over
- A "Speed" checkbox was added to the control panel, which toggles visibility of a speedometer
- The speedometer was added to the center of the cart, showing speed of the moving cart

**Comment by jessegreenberg** [comment]
@zepumph, assigning to you, but please let me know if you have any questions about the above request.

**Comment by zepumph** [comment]
I looked into this today. I found only one small place where more instrumentation was needed. Good work @jessegreenberg instrumenting as you go! I am a bit confused about what it next. We want to release FAMB and FAMB-phetio now together? I can make releases very soon to go off to the QA team.

**Comment by jessegreenberg** [comment]
Great, thanks @zepumph!

> We want to release FAMB and FAMB-phetio now together (in separate branches but with the same shas)

Yes, that seems correct.  Let me know if you would like some help preparing RCs.

**Comment by zepumph** [comment]
I will carry this on in #227 and let @oliver-phet know when they are published.

**Comment by zepumph** [comment]
Are we good to close this issue? It seems like it to me.
