### ISSUE TITLE
Publish new phet and phet-io versions 

### ISSUE THREAD

**Issue by zepumph** [phetsims/forces-and-motion-basics#227]
Because of the added features in #220, it would be good to release new production versions of this Sim.  It looks like these will be 2.3 and 2.3-phetio

**Comment by jessegreenberg** [comment]
@zepumph, are phetio branches supposed to increment the minor number? I remember some confusion in balloons-and-static-electricity about having 1.2 and 1.2-phetio branches, but maybe that was for another reason. Sorry, I could be wrong, I don't have a full understanding of the phetio build process.

**Comment by jessegreenberg** [comment]
Or maybe since they are being built from the same SHAs they are supposed to have same minor number?

**Comment by zepumph** [comment]
>@zepumph, are phetio branches supposed to increment the minor number? 

Yeah you are right on. We want to make sure that we always increment. Let's say we were only releasing a phet brand rc for FAMB. Since there is a 2.2-phetio (even though no 2.2), we would still have to use 2.3 because we increment regardless of the brand. 

Since we are pulling both at the same time (same shas), it would make sense for them to share shas.

**Comment by zepumph** [comment]
They are in the queue now.

**Comment by jessegreenberg** [comment]
Ok, thanks @zepumph, so should the branches be 2.3 and 2.4-phetio?

**Comment by zepumph** [comment]
I don' think so because we want them to share the same shas, and stay in sync. Feel free to call if we want to discuss further.

**Comment by phet-steele** [comment]
@zepumph we MUST take a new screenshot before publication. I'll take care of it when this rc is closer to being done, but let's not forget. See #228.

**Comment by zepumph** [comment]
Thanks a ton. I will make this more obvious in the deployment guidelines.

**Comment by phet-steele** [comment]
> @zepumph we MUST take a new screenshot before publication. I'll take care of it when this rc is closer to being done, but let's not forget. See #228.

Screenshot is done.

**Comment by zepumph** [comment]
@jessegreenberg you really took this one over. It is possible that this can be closed now. What is the status here? What can I do to help?

**Comment by jessegreenberg** [comment]
Thanks @zepumph, this is mostly being continued in #235. Next steps are to cherry pick in commits for some fixes in dependencies. Then once https://github.com/phetsims/QA/issues/57, we will be ready for a spot check rc.

**Comment by jessegreenberg** [comment]
2.3.0-phetio was published today. @zepumph @samreid can this be closed or is there more to do? Going through sim_deployment.md, I started to go through the PRODUCTION FOR PHET_IO_BRAND steps, but I am not sure if items 1 or 3 need to be done.

**Comment by zepumph** [comment]
I think that the goal of this issue (publishing for both brands) was back before our full quest was set on stable apis in phet-io. As a result I think that holding out on the phet-io version is the best way to progress. We can revisit when famb is ready for stabilization. Closing.
