### ISSUE TITLE
Flag overlaps text when Sum of Forces is zero

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#230]
After #213, the flag does not overlap the Sum of Forces if and only if the sum is NOT zero. If it is zero, The "Sum of Forces = 0" string is still high on the screen and is covered by the flag:

<img width="1915" alt="screen shot 2017-06-29 at 10 41 14 am" src="https://user-images.githubusercontent.com/5863899/27699439-868c6c2e-5cb7-11e7-8992-7ba44fa34e50.png">

Because the string is higher...
<img width="1639" alt="screen shot 2017-06-29 at 10 40 43 am" src="https://user-images.githubusercontent.com/5863899/27699446-8e2bb23c-5cb7-11e7-8e59-30ce0e70e935.png">

...than the non-zero string
<img width="1718" alt="screen shot 2017-06-29 at 10 40 53 am" src="https://user-images.githubusercontent.com/5863899/27699463-96fabf48-5cb7-11e7-8535-80a05dce24ad.png">

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/11.
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.2/forces-and-motion-basics_en.html
Version: 2.3.0-rc.2 2017-06-27 18:03:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"12510072","branch":"HEAD"},"babel":{"sha":"e35168a3","branch":"master"},"brand":{"sha":"b630f897","branch":"HEAD"},"chipper":{"sha":"57453afd","branch":"HEAD"},"dot":{"sha":"3d9d2f3d","branch":"HEAD"},"forces-and-motion-basics":{"sha":"037799d5","branch":"HEAD"},"joist":{"sha":"aa108052","branch":"HEAD"},"kite":{"sha":"c9b529a2","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"197b02b3","branch":"HEAD"},"scenery-phet":{"sha":"727d5bd7","branch":"HEAD"},"sherpa":{"sha":"0207b055","branch":"HEAD"},"sun":{"sha":"794481f1","branch":"HEAD"},"tandem":{"sha":"f3949f64","branch":"HEAD"},"vibe":{"sha":"b69e96db","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
@phet-steele, this is the behavior in master and the deployed version too correct?

**Comment by phet-steele** [comment]
> this is the behavior in master and the deployed version too correct?

Yup, @arouinfar agrees this should be changed

**Comment by jessegreenberg** [comment]
@arouinfar @phet-steele so the change should be that the "Sum of forces = 0" should be vertically aligned with the "Sum of Forces" string, correct?

**Comment by arouinfar** [comment]
Correct @jessegreenberg!

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar!

**Comment by phet-steele** [comment]
👍
