### ISSUE TITLE
Cart can go beyond stoppers

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#231]
Found by @phet-steele for https://github.com/phetsims/QA/issues/11.  @phet-steele please feel free to include additonal information if stuff is missing.

Steps to reproduce:
- Start a game of tug of war where the cart will move to one side
- Just before cart wheel hits edge of stopper navigate away from current browser tab.
- Return to sim tab.

The cart wheel will be beyond the stopper.

@phet-steele EDIT: good to note that switching browser tabs earlier than "just before the edge of the stopper" doesn't have the same result.

**Comment by jessegreenberg** [comment]
This is also a problem in the deployed version, here is a screenshot in 2.1.4:

![capture](https://user-images.githubusercontent.com/6396244/27704811-04c5f84c-5cc9-11e7-9224-08d14d55df41.PNG)

**Comment by jessegreenberg** [comment]
Should be fixed in the above commit.

**Comment by jessegreenberg** [comment]
@phet-steele, sorry, It looks like I forgot to link to this in https://github.com/phetsims/QA/issues/11.  Was this verified as fixed in https://github.com/phetsims/QA/issues/11?

**Comment by jessegreenberg** [comment]
Ahh, nevermind @phet-steele I misunderstood the closing comment in https://github.com/phetsims/QA/issues/11, because this issue was *found* in https://github.com/phetsims/QA/issues/11.  So 2.3 was never ready for release, but ready for a spot check.  But will need a new RC anyway for #235.

**Comment by jessegreenberg** [comment]
Assigning to myself to verify as fixed in the next RC.

**Comment by phet-steele** [comment]
Fixed as far as I can tell.
