### ISSUE TITLE
Does lastLocationProperty have the wrong phetioValueType?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#237]
lastLocationProperty looks to be instrumented as a TVector2, but in `NetForceModel.js` it is only being set with a string value. This could explain why in Instance Proxies and Events wrappers, the value never changes. It doesn't change when moving pullers to their knots or to their home; it should. It's probably expecting x & y values but receiving a string instead...so it has no support to display that value. This is just an assumption further supported by the documentation saying this accepts a string:

```js
  // @public {string} - a classified location in the play area
    // TODO: What are the valid values for this Property?
    this.lastLocationProperty = new Property( 'home', {
      tandem: tandem.createTandem( 'lastLocationProperty' ),
      phetioValueType: TVector2
    } );
```
Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/42.

**Comment by jessegreenberg** [comment]
Yes, it should be TString, thanks @phet-steele.  It has been TVector2 for a while, probably because the Property  name makes this sound like a Vector2.

**Comment by jessegreenberg** [comment]
Looks like valid values are 'knot' and 'home'.  So maybe should we rename to lastPlacementProperty?

**Comment by jessegreenberg** [comment]
If I rename the Property, clients will need to update their wrappers when upgrading to the new version. Is this acceptable?  Renaming the Property would presumably make it easier to understand what this Property is doing for both PhET-iO clients and sim maintainers.

**Comment by jessegreenberg** [comment]
Leaning toward not renaming until we have documentation that clients can use to be notified of breaking changes.

**Comment by jessegreenberg** [comment]
Would the change from TVector2 to TString potentially break wrappers anyway?  @samreid what would you recommend in this case?

**Comment by samreid** [comment]
We do not need to maintain a stable API yet, we should focus on naming and typing things as they should be.

**Comment by jessegreenberg** [comment]
Thanks @samreid, sounds good.

**Comment by jessegreenberg** [comment]
Changes cherry-picked into release branches.

**Comment by phet-steele** [comment]
Nice! Fixed.
