### ISSUE TITLE
[State] Pusher direction not being transmitted when fallen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#238]
1. Go to http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.3/wrappers/state/state.html?sim=forces-and-motion-basics&relativeSimPath
2. In the Motion screen, use the arrows to apply force on the cart TO THE RIGHT.
3. Just as the cart reaches max speed and the pusher falls, pause the sim.
4. When comparing between the top and bottom screen, the pusher is facing left in the bottom when it should be facing right. The pushers do however match if you pushed to the left in step 2. Looks like the fallen pusher in the bottom sim will ALWAYS be facing left when fallen.

![screen shot 2017-08-24 at 1 42 02 pm](https://user-images.githubusercontent.com/5863899/29685286-38c0e8d4-88d2-11e7-8a3d-8779e820b2f0.png)

Seen on macOS 10.12.6 Chrome. For phetsims/QA#42.

**Comment by jessegreenberg** [comment]
Verified that this is an issue for 2.2-phetio so this is likely not a problem from #226.

**Comment by jessegreenberg** [comment]
Sometimes it doesn't happen when stepping through. Wondering if this is happening because of the refresh rate of the "state" sim?
![capture](https://user-images.githubusercontent.com/6396244/29692700-9e8f6174-88ee-11e7-986f-2b473a220771.PNG)

**Comment by samreid** [comment]
In the top pic, notice the mountains on the right hand side are different in source vs destination frames.

![image](https://user-images.githubusercontent.com/679486/29745615-e6bc8e6a-8a7c-11e7-87d6-6d4b27178aa7.png)

**Comment by samreid** [comment]
After investigating this for 20 minutes I think we should (a) have @jessegreenberg and @samreid collaborate to investigate further or (b) note it as a known defect and publish anyways--may not be too severe.

Also, I noticed that pressing "Launch" there is no pusher at all:

![image](https://user-images.githubusercontent.com/679486/29745632-707798ac-8a7d-11e7-8149-340ae57618a0.png)

**Comment by ariel-phet** [comment]
The pusher direction is an inconsequential detail once the pusher has fallen off.

Marking as "wontfix" - feel free to close @samreid or @jessegreenberg

**Comment by jessegreenberg** [comment]
@samreid since this is a phet-io issue should this be closed or left open for documentation?

**Comment by samreid** [comment]
I think `wontfix` issues should be closed.  We can still view them (if we remember to look), but open issues should be for issues we plan to work on.  Closing.
