### ISSUE TITLE
Track doesn't show it's disabled with an empty stack

### ISSUE THREAD

**Issue by phet-steele** [phetsims/forces-and-motion-basics#242]
1. Go to http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.3/wrappers/state/state.html?sim=forces-and-motion-basics&relativeSimPath
2. Go to the Motion screen
3. Take all objects off the track. The track in the top sim correctly turns gray; the bottom sim's track remains white

![screen shot 2017-08-24 at 3 07 18 pm](https://user-images.githubusercontent.com/5863899/29688733-effeb80e-88dd-11e7-8dd2-92110cbc0256.png)

Seen on macOS 10.12.6 Chrome. For phetsims/QA#42.

**Comment by phet-steele** [comment]
@jessegreenberg just a hunch, but it might be that only `forcesAndMotionBasics.{{SCREEN}}.view.appliedForceSlider.sliderKnob.enabledProperty` is instrumented, but not also the track.enabledProperty (or equivalent).

**Comment by jessegreenberg** [comment]
@phet-steele yes, I think you are right.  It looks like both ```enabledProperty``` in sun/HSliderTrack and sun/HSlider is not instrumented. The ```enabledProperty``` is shared between both (passed through options).

Temporary solution is to  pass an instrumented ```enabledProperty``` to ```HSlider``` in ```AppliedForceSlider```.

**Comment by jessegreenberg** [comment]
That fixes it, but I am wondering if this should be handled in Sun?

![capture](https://user-images.githubusercontent.com/6396244/29730731-a96614ca-899e-11e7-83b6-176990fe01d8.PNG)

**Comment by jessegreenberg** [comment]
Being investigated in https://github.com/phetsims/sun/issues/310, on hold until we investigate that issue.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/sun/issues/310 was closed, this issue should be fixed.

**Comment by jessegreenberg** [comment]
Verified fixed in master, removed  custom code in AppliedForceSlider.

**Comment by jessegreenberg** [comment]
2.3-phetio and 2.3 have sun sha 50f640e713ff6c764ec1484fb546370c18abe1ad.

To pick up this fix they need changes through 96c223b3fb271992069088e4d48019b141c9191c

**Comment by jessegreenberg** [comment]
Changes between those SHA's seem either related to this issue, are adding documentation, or were for sorting require statements, so it seems safe to update the shas in dependencies.json without creating release branches in sun.

**Comment by jessegreenberg** [comment]
Both also require an updated DOT sha to include TRange db33a2c7fca14980bccd7d9517839c5b8ae7a9ee

**Comment by jessegreenberg** [comment]
Should be fixed in release branches.

**Comment by phet-steele** [comment]
Beautiful, fixed.
