### ISSUE TITLE
Text overlap when applied force changes direction (Friction)

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/forces-and-motion-basics#245]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.4

**Browser:**

Safari 10.1

**Problem description:**

In the Simulation wrapper, a text overlap will occur if the Forces box and the Values box in the Friction screen are checked, the masses are moving fairly quickly, and suddenly force is applied in the direction opposite the movement of the masses. Discovered while testing phetsims/QA/issues/42. I checked the published version; the overlapping occurs in it as well.

**Steps to reproduce:**

1. Add two crates.
2. Increase applied force to maximum.
3. Once the crates are traveling at 40 m/s, apply force in the direction opposite the movement.
4. Notice how the text "Applied Force" overlaps with the value for the Friction Force just as the direction of the applied force changes.

Screenshots:
![screen shot 2017-08-24 at 4 26 23 pm](https://user-images.githubusercontent.com/31285590/29691713-84ca8020-88e9-11e7-872b-ddca5cfccfac.png)

Troubleshooting information (do not edit):
Name: ‪Forces and Motion: Basics‬
URL: https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html
Version: 2.1.4 2017-08-15 08:05:23 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
Language: en-US
Window: 1440x736
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.24.45)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"1e0ba48a","branch":"master"},"brand":{"sha":"853b3b17","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"679f2e0b","branch":"HEAD"},"joist":{"sha":"65cda5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"7bad0484","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"182dae83","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"200263ae","branch":"HEAD"},"vibe":{"sha":"0b1c33f9","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet.  It looks like this issue is not specific to this version.  @arouinfar @ariel-phet can you please advise on whether or not this should be fixed and what the fix to the layout should be?

**Comment by arouinfar** [comment]
Looks like the label location depends on the the arrow size and proximity to other labels.

(1) When there's enough room, the magnitude is inside of the arrow.
<img width="448" alt="screen shot 2017-08-24 at 10 30 17 pm" src="https://user-images.githubusercontent.com/8419308/29699741-48a96588-891c-11e7-8ab9-8545c00e468c.png">

(2) The magnitude moves below "Applied Force" when the arrow becomes too small.
<img width="403" alt="screen shot 2017-08-24 at 10 30 24 pm" src="https://user-images.githubusercontent.com/8419308/29699742-48aa3b98-891c-11e7-8e7a-3c6715440567.png">

(3) When the vectors in are in the same direction, the "Friction Force" is bumped below the arrow, and there's generally occlusion issues with at least one of the values.
<img width="250" alt="screen shot 2017-08-24 at 10 52 21 pm" src="https://user-images.githubusercontent.com/8419308/29700062-ecf815ec-891e-11e7-8316-2088757e8d1f.png"> <img width="185" alt="screen shot 2017-08-24 at 10 30 36 pm" src="https://user-images.githubusercontent.com/8419308/29699740-48a943b4-891c-11e7-92c1-626701af91a3.png">  <img width="200" alt="screen shot 2017-08-24 at 10 53 29 pm" src="https://user-images.githubusercontent.com/8419308/29700084-10aea014-891f-11e7-9584-77a47a51fac6.png">


Perhaps when the forces are in the same direction, it'd be best to always display the magnitude of the force below the force name, as with the "Applied Force" in the scenario (2). That way the strings/values would never collide.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, that is a good idea, here is what that looks like
![capture2](https://user-images.githubusercontent.com/6396244/29725508-976ad8a6-8989-11e7-96b0-3c2eb757ab48.PNG)

We could also alilgn horizontally to give the mass a little space:
![capture](https://user-images.githubusercontent.com/6396244/29725663-17b005fe-898a-11e7-8a93-e05b9ae902e7.PNG)

**Comment by arouinfar** [comment]
@jessegreenberg I really like the 2nd screenshot in https://github.com/phetsims/forces-and-motion-basics/issues/245#issuecomment-324989181 with the magnitude of the Friction Force next to the string.

**Comment by arouinfar** [comment]
I took a look at master, and it looks like you went with the 2nd option. Overall, looks good, but we'll need to also handle cases like this:

![image](https://user-images.githubusercontent.com/8419308/29731837-52b5538e-89a3-11e7-8252-72c5cdcf0a6d.png)

**Comment by jessegreenberg** [comment]
It looks like this was handled before by switching the layering order of the friction and applied force arrows so the readout of the friction force could be seen while the value of applied force could be inferred by relative size. If the applied force arrow is always on top, will that fix the problem? That would be the easiest solution.

**Comment by jessegreenberg** [comment]
All text is visible but it looks a little weird.
![capture](https://user-images.githubusercontent.com/6396244/29732697-056e2ade-89a7-11e7-8590-24e306f9f6bf.PNG)

**Comment by arouinfar** [comment]
@jessegreenberg https://github.com/phetsims/forces-and-motion-basics/issues/245#issuecomment-325034517 does look a bit weird. 

I think it would be fine to always arrange the text like this (when the vectors are in the same direction), regardless of the vector size.
![image](https://user-images.githubusercontent.com/8419308/29732792-7a7499c6-89a7-11e7-9ff0-eec7624e56e7.png)

**Comment by jessegreenberg** [comment]
Thanks @arouinfar that looks good to me.  Added in the above commit, can you review in master again?

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg!

**Comment by jessegreenberg** [comment]
Excellent, thanks! I am going to keep open just as a reminder to bring commits into the release branches.

**Comment by arouinfar** [comment]
Oops, sorry about that @jessegreenberg!

**Comment by jessegreenberg** [comment]
Merged into 2.3 and 2.3-phetio release branches

**Comment by phet-steele** [comment]
I think this is working!
