### ISSUE TITLE
Flag disposal problem

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#246]
From https://github.com/phetsims/phet-io/issues/722

@jessegreenberg said:

@mattpen I think the line ```flagNode && flagNode.dispose();``` in https://github.com/phetsims/phet-io/issues/722#issuecomment-255418829 is part of the cause of a disposal issue in forces-and-motion-basics (221).

Can this line be removed?  It seems like the only way to update the cart position or change ```model.stateProperty``` after a team wins is to press the "Reset All" button or "Return" button, and both will also trigger FlagNode disposal.

Are there wrappers where the FlagNode needs to be disposed before pressing "Reset All" or "Return"?

**Comment by samreid** [comment]
@mattpen replied:

@jessegreenberg 

> It seems like the only way to update the cart position or change model.stateProperty after a team wins is to press the "Reset All" button or "Return" button

I think this is true when using the sim itself, but we have cases where we are resetting the cart and pullers due to actions in the classroom-activity wrapper (switching tabs or restoring states).  I don't think the line can simply be removed without breaking the wrapper.  It looks like you may have discovered a solution in https://github.com/phetsims/phet-io/issues/722.  Is this working in the general case? Should I test it in the wrapper?

**Comment by jessegreenberg** [comment]
I believe that the disposal was added back in https://github.com/phetsims/forces-and-motion-basics/commit/71d78d94b3d8a6188dc14d2f80f0a8271f4c8ba4 for #221. I will try to reset the cart and the sim in the classroom activity wrapper and make sure that the flag is being disposed in those cases before closing.

**Comment by jessegreenberg** [comment]
I verified in the classroom-activity wrapper that we are disposing the flag whenever we switch tabs or restore states.  Closing.
