### ISSUE TITLE
Sum of forces arrow and kilogram text overlap (Friction)

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/forces-and-motion-basics#247]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6

**Browser:**

Safari 10.1.2

**Problem description:**

The sum of forces arrow overlaps with the x kilogram text when sufficient force is applied. The applied force and friction force arrows just barely overlap with the x kilogram text. Found this while testing PhET-iO in the simulation wrapper. Should be an easy fix. I would move the "Sum of Forces" text and the sum of forces arrow up, and I would move the "Applied Force" and "Friction Force" texts and their respective arrows down just a bit. This is for phetsims/QA/issues/42.

**Steps to reproduce:**

1. Open the sim.
2. Add two crates. (Or any other combination of masses.)
3. Check all boxes except the speed box. (Or you can check the speed box, but it's not necessary.)
4. Apply maximum force.
5. You should notice that the sum of forces arrow overlaps slightly with the x kilogram text. If you look carefully, the applied force and friction force arrows overlap with the x kilogram text just a little bit.

**Screenshots:**

![screen shot 2017-08-29 at 2 39 33 pm](https://user-images.githubusercontent.com/31285590/29843036-ec6ee040-8cc7-11e7-9bca-9d5ca7c15a9d.png)

------------------------------------------------------------------------------------------------------

![screen shot 2017-08-29 at 2 39 21 pm](https://user-images.githubusercontent.com/31285590/29843045-f1acdf1c-8cc7-11e7-89a8-b4b0974d9c39.png)

**Troubleshooting information (do not edit):**

Name: ‪Forces and Motion: Basics‬
URL: https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html
Version: 2.1.4 2017-08-15 08:05:23 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Language: en-US
Window: 1440x736
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.25.17)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"1e0ba48a","branch":"master"},"brand":{"sha":"853b3b17","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"forces-and-motion-basics":{"sha":"679f2e0b","branch":"HEAD"},"joist":{"sha":"65cda5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"7bad0484","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"182dae83","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"200263ae","branch":"HEAD"},"vibe":{"sha":"0b1c33f9","branch":"HEAD"}}

**Comment by lmulhall-phet** [comment]
Amateur hour ^^^^. Sorry about that. Hopefully everything is OK now.

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet.  @ariel-phet is this something that needs to be addressed?

**Comment by lmulhall-phet** [comment]
You're welcome @jessegreenberg. I know it's a small thing, but I'm not sure what I should and shouldn't point out yet.

**Comment by jessegreenberg** [comment]
@lmulhall-phet I think everything should be pointed out, I appreciated it! I just want to make sure @arouinfar and @ariel-phet agree it is worth some time.  Though I agree it does look like this could be a quick thing to change.  @arouinfar @ariel-phet thoughts on @lmulhall-phet suggested fix?

> I would move the "Sum of Forces" text and the sum of forces arrow up, and I would move the "Applied Force" and "Friction Force" texts and their respective arrows down just a bit.

**Comment by arouinfar** [comment]
> @lmulhall-phet I think everything should be pointed out

Agreed! Thanks @lmulhall-phet.

> I would move the "Sum of Forces" text and the sum of forces arrow up

That would fix the occlusion problem for most situations, except for when the fridge is on the bottom. ("Sum of Forces" would overlap the mass.)
<img width="203" alt="screen shot 2017-08-29 at 4 49 20 pm" src="https://user-images.githubusercontent.com/8419308/29847740-80459e46-8cda-11e7-9805-add8a2a564a6.png">

>  and I would move the "Applied Force" and "Friction Force" texts and their respective arrows down just a bit.

I think these vectors are purposely aligned with the pusher's hands, so that the applied force looks like it's coming from the pusher. Generally, the vectors would be drawn from the center of mass, but since this sim targets a younger audience I think it makes sense to keep them aligned to the hands.

Perhaps we could instead try reducing the opacity of the vectors a bit so that the occluded values could still be read, such as the "50 kg" in this case.
<img width="257" alt="screen shot 2017-08-29 at 4 50 09 pm" src="https://user-images.githubusercontent.com/8419308/29847858-f7bfaafc-8cda-11e7-8974-8b293aa97a0a.png">

Any thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
@lmulhall-phet just reiterating, I think in general always good to point out what you find. As a rule of thumb, anything you think could be a bug OR a hindrance to student use is worth pointing out. We can always discuss or say "yes this is a known issue" or such, but in general we really like QA to take ownership and point out what they feel is potentially an issue.

In this particular case, it would be difficult to find a position for the vectors that would accommodate all situations. More importantly, I think that no pedagogical issues arise from this occlusion. It is easy to get the mass information before the experiment, by stopping any application of force, or by grabbing one of the objects. I think being able to see the mass label during pushing or such is not critical.

Closing.
