### ISSUE TITLE
Getting error when Interaction Scale Property slider hits 0

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/forces-and-motion-basics#248]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6

**Browser:**

Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Problem description:**

In the Instance Proxies wrapper, I'm getting an error when I make the Interaction Scale Property slider go to 0. This is for phetsims/QA/issues/42.

**Steps to reproduce:**

1. Open the Instance Proxies wrapper.
2. Select the Motion screen.
3. Copy and paste the following into ctrl-f: forcesAndMotionBasics.motionScreen.model.fridge.interactionScaleProperty: TProperty.<TNumber>
4. Move the slider down to 0.
5. You should notice that the refrigerator is floating in the sky, and you should be getting an error.

**Screenshots:**

![screen shot 2017-08-29 at 4 24 11 pm](https://user-images.githubusercontent.com/31285590/29846973-8c576312-8cd6-11e7-8fa8-3aafd2e2137c.png)

**Comment by jessegreenberg** [comment]
@ariel-phet @samreid should this issue be worked on at this time?

**Comment by jessegreenberg** [comment]
Was a quick thing to  change.

**Comment by jessegreenberg** [comment]
Fixed merged into release branch.

**Comment by jessegreenberg** [comment]
Merged into 2.3 as well.

**Comment by phet-steele** [comment]
Fixed.
