### ISSUE TITLE
performance is poor on Nexus 7

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#25]
http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.0.0-rc4/forces-and-motion-basics.html
Android 4.3
Firefox 23
Chrome 28.0.1500.94

Sim is frustrating to use, to the point of being unusable. Friction slider is especially bad.

**Comment by samreid** [comment]
Performance is markedly faster and smoother in Chrome 43.0.2357.93 on Android 5.1.1 on Nexus 7.  Everything seems usable, friction slider (still the slowest part of the sim) gets about 10 frames per second--not great, but usable.  Closing.
