### ISSUE TITLE
branch: layout-change

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#253]
Identified by `print-branches.sh`. @samreid please describe.

**Comment by jessegreenberg** [comment]
This one was also mine. In https://github.com/phetsims/forces-and-motion-basics/issues/213, the layout was being changed and it was unclear whether or not we would keep the changes. It was decided changes were beneficial so this branch has been merged with master. It can be deleted.

**Comment by jessegreenberg** [comment]
This has been re-deleted for https://github.com/phetsims/special-ops/issues/198
