### ISSUE TITLE
branch: no-end-game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#254]
Identified by `print-branches.sh`. @samreid please describe.

**Comment by jessegreenberg** [comment]
This one was mine. For https://github.com/phetsims/forces-and-motion-basics/issues/220 we were playing with the idea of allowing the cart to move off screen indefinitely after a team won. That idea has been abandoned. I just deleted this branch.

**Comment by jessegreenberg** [comment]
This has been re-deleted for https://github.com/phetsims/special-ops/issues/198
