### ISSUE TITLE
Add semi-transparent background behind Force Value when outside of vector

### ISSUE THREAD

**Issue by arouinfar** [phetsims/forces-and-motion-basics#257]
In working on #256, I noticed that the Force Values can be a bit hard to read at times.

![image](https://user-images.githubusercontent.com/8419308/41367465-5a682d10-6efc-11e8-8322-9cefb1c00723.png)

One strategy we've used in other sims is to add a semi-transparent background behind the value to improve its readability. We could add a background similar to the Mass Values, but at 50% opacity and a bit less vertical padding. This would only be necessary when the vector is too small/occluded to fit the value within.

![image](https://user-images.githubusercontent.com/8419308/41368542-7c34219e-6eff-11e8-8da3-428732da130c.png)

![image](https://user-images.githubusercontent.com/8419308/41368431-2ab7965c-6eff-11e8-9db5-8a3bdf8a33a6.png)

Next time a dev spends some time on FAMB, this would be a nice tweak. Do you agree @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar  - I agree. Leaving open and unassigned.

**Comment by amanda-phet** [comment]
This seems reasonable to address with https://github.com/phetsims/forces-and-motion-basics/issues/304

**Comment by AgustinVallejo** [comment]
Adding the feature, it currently looks like this (Background only appears when the value doesn't fit within the arrow)

![image](https://github.com/phetsims/forces-and-motion-basics/assets/37052186/f33ef982-33a9-4191-9ad3-de6b50547bb2)

Please review and close if it looks OK, otherwise let me know how I can improve it. @arouinfar @amanda-phet

**Comment by arouinfar** [comment]
@AgustinVallejo the background behind the values generally looks good. Is it possible to dynamically size the labels? If the value is < 100N, there is some extra whitespace.

<img width="389" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/8419308/73e14c8c-ca54-48cd-84e3-196222496654">

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/forces-and-motion-basics/assets/37052186/d899238a-9a99-4862-8adb-c47e386dd474)

Looking like this since the above commit. Let me know if that's better

**Comment by arouinfar** [comment]
Looks much better now, thanks @AgustinVallejo!

**Comment by amanda-phet** [comment]
Thanks for reviewing @arouinfar . I think this looks good too!
