### ISSUE TITLE
Use VerticalCheckBoxGroup in MotionControlPanel

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#258]
Discovered in https://github.com/phetsims/sun/issues/344, Forces and Motion: Basics is using VerticalCheckBoxGroup in NetForceControlPanel but not MotionControlPanel.  Here's a picture of MotionControlPanel:

![image](https://user-images.githubusercontent.com/679486/44639798-0ed96580-a97b-11e8-8f51-06b9fe4be2a1.png)

Note this means that MotionControlPanel:
(a) doesn't have the right mouseArea for the checkboxes (should extend all the way to the right, like in the NetForceControlPanel)
(b) duplicates and deviates from common code functionality
(c) has an inconsistent implementation compared to NetForceControlPanel

Assigning to @ariel-phet for prioritization/timeline/delegation.

**Comment by ariel-phet** [comment]
@zepumph is this something you could handle? Seems like it would be beneficial for both iO and a11y, and @DianaTavares plans to use FAMB for the next dashboard study, so seems in your wheelhouse.

**Comment by zepumph** [comment]
I'll try to crank this out on thursday.

**Comment by zepumph** [comment]
I was able to convert this and it worked easily, simplifying the code a bit too. 

Note that I dropped support for the instrumented enabledProperty in `MotionScreenView` in favor of a general solution to be implemented in https://github.com/phetsims/sun/issues/387.

@ariel-phet please assign a reviewer.

**Comment by samreid** [comment]
May I please review this change? I have familiarity with FAMB as well as VerticalCheckboxGroup.  @ariel-phet please assign me if that seems reasonable.

**Comment by ariel-phet** [comment]
All you @samreid

**Comment by zepumph** [comment]
Like stated in https://github.com/phetsims/sun/issues/387#issuecomment-418797525, we may want to make sure that we are using the new default enabledProperty for Checkbox in this control panel.

**Comment by samreid** [comment]
Code change looks great and I tested that everything's working nicely.  The new version also has the touch areas extend to the right (for short texts), which seems like an improvement.
