### ISSUE TITLE
[phet-io 2.1.11-rc.1] dev link on wrapper index broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/forces-and-motion-basics#262]
From https://github.com/phetsims/QA/issues/187

I am finding some weird logic with the devguide for this version.

You can get to it via https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.11-rc.1/wrappers/index/

When you do so, it redirects you to "https://phet-dev.colorado.edu/guide.html" which is not a file.
I see that it works in the previous version:
https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.10-phetio/docs/devguide.html

When I `curl -v https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.11-rc.1/docs/devguide.html`, I get that it has moved to "https://phet-dev.colorado.edu/guide.html" which doesn't exist.

I CAN recreate this problem in the last rc on phet-dev that 2.1.10 went through:
https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.10-rc.1/wrappers/index/

@mattpen is it possible that there is a weird redirect rule in place for some reason on this server? Perhaps something to do with the "dev" keyword?

**Comment by zepumph** [comment]
This is not a high priority to me because it doesn't look like it will effect production, and it won't effect the upcoming study.

**Comment by mattpen** [comment]
@zepumph - How do I recreate this?

![image](https://user-images.githubusercontent.com/11747676/45561733-ac4ee900-b805-11e8-9b75-4a3804bcf270.png)

```
$ curl -u ***:**** -sI https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.11-rc.1/wrappers/index/
HTTP/1.1 200 OK
Date: Fri, 14 Sep 2018 16:05:53 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips
Vary: Cookie
Last-Modified: Wed, 12 Sep 2018 21:40:37 GMT
ETag: "172c-575b370e1df40"
Accept-Ranges: bytes
Content-Length: 5932
Content-Type: text/html; charset=UTF-8
Connection: close
```

**Comment by mattpen** [comment]
@zepumph - I think this line is missing a `^` to match the beginning of the string:

 `RewriteRule "/dev(.*)" "$1" [L,R=301,NE]`

It should be:

`RewriteRule "^/dev(.*)" "$1" [L,R=301,NE]`

I'll make this change and deploy it tonight after the scheduled cache server reboot.

**Comment by zepumph** [comment]
Ahh I see. Yes sounds like a good fix.

**Comment by zepumph** [comment]
Also maybe a slash after 'dev'?

**Comment by mattpen** [comment]
> Also maybe a slash after 'dev'?

Should we then add a rule rewriting `/dev` -> '/'?

**Comment by mattpen** [comment]
> Couldn't you away with a single rule like (untested) RewriteRule "^/dev(/.*)" "$1" [L,R=301,NE]

Indeed we can.  It should be working now.  Please close if all looks good @zepumph.

**Comment by zepumph** [comment]
That's great thanks! Just a note that the previous 301 is a very stubborn redirect that is cached permanently, so you need to open dev tools or something if testing this when you have already been to that link. Closing
