### ISSUE TITLE
phet-io.emitStatesInterval performance issues on Mac

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#264]
For https://github.com/phetsims/QA/issues/187
When investigating Step 2 on Mac OS 10.13, Both firefox and safari lagged and, in safari's case, crashed when the console was open to view ```"event": "state"```.  Chrome on Mac OS 10.13 showed some slow down, but was much better.
In addition, firefox was very hard to find ```"event": "state"``` as it seemed to be in a different type of text that the filter could not recognize.  This occurs in Win 10 firefox too, but without the lag.
Video of Firefox
https://drive.google.com/file/d/1wsjnxbspycn-ZNJ36wpoIol7LWnup3dy/view?usp=sharing

**Comment by zepumph** [comment]
What about if you just search for "state"? Also i recommend clearing the console every so often to keep the total size of the console down (perhaps that will help laggyness).

**Comment by KatieWoe** [comment]
Tried that and it didn't work either.  I tried to clear the console, but its slowing down and, in safari's case, crashing so fast that it doesn't make a difference.

**Comment by zepumph** [comment]
@katie and I looked at this this morning, and found that indeed the ability to search for the state events is weird and difficult. I'm not sure how to proceed with that but to note it and move on.

>Elaboration on Safari performance part of issue. The time from starting the sim to crash is about 15 seconds, depending on how much the sim is manipulated. The console shows some activity, seems to stall when the sim is manipulated, and almost immediately crashes and refreshes the page to the code enter screen with an error message. Since this happens almost as soon as manipulation begins, refreshing the console doesn't work. Using the page without the console open does not seem to cause any issue and the sim does not crash.

This seems to be covered now by https://github.com/phetsims/forces-and-motion-basics/issues/265. 

I don't think that else needs to be done for the rest of this issue closing.

**Comment by KatieWoe** [comment]
Firefox experiences this same large amount of slow down on Win 10.
For https://github.com/phetsims/QA/issues/192
