### ISSUE TITLE
ready links for FAMB study

### ISSUE THREAD

**Issue by zepumph** [phetsims/forces-and-motion-basics#268]
2.1.11-phetio was published in #267, from here we just need to put together the final links, and test as much as possible.

@DianaTavares here are two example links to embed in your assignment, one for console recording, and one (live) for actual metacog recording:

```
<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.11-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=This%20is%20a%20test&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-test&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&console" target="_blank">Link to Forces And Motion: Basics Simulation to console recording</a>


<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.11-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=This%20is%20a%20test&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-test&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">Link to Forces And Motion: Basics Simulation to metacog recording (feel free to record a few sessions, this is to a testing site)</a>
```

@DianaTavares to proceed please:
- [x]  Test adding these links to the assignment, does this format work as you expect/like?
- [x] Please tell me what you want the prompt to be
- [x] I need 4 (or however many) different ids to keep the sessions/assignments separate.

Just note that the metacog link above is live, and will record, feel free to record a few sessions if you want. I'll make sure all is working as expected.

After this all we should need to do is 
- [x]  all the testing we feel is necessary/desired (QA hit the recording process pretty hard without many issues YAY)
- [x] Construct the 4 exact links
- [ ] make the wrapper public for students to use.

**Comment by DianaTavares** [comment]
Amazing! thanks! 
It's going to be only two links 2010_exploration and 2010_guided to get the session separate. 

I am going to check both links this weekend. I remember that it was an special login to identify easy the data that was for testing when is using the live link. Could you remind me of the login key?

I don't know what do you mean by 

> Please tell me what you want the prompt to be

**Comment by zepumph** [comment]
The prompt is the text that is displayed in the login wrapper, right now it says "This is a test"

> Could you remind me of the login key?
I can, but you will need to talk to me privately.

**Comment by zepumph** [comment]
Oh wait. I missunderstood you before.

As a learner Id we sometimes had people use `phettest`, but this version doesn't support that, so feel free instead to use any 7 digit number. Again these sessions won't mix with you data, so don't worry.

**Comment by DianaTavares** [comment]
Perfect, thanks!!

**Comment by DianaTavares** [comment]
Hi Michael!

the links in the activity works perfect!! (I save two sessions using the live link). The console link get slow some times, but I guess that is because is displaying all that information. That don't happen with the live link.

the prompt (text) in the link just have to say "link to the simulation Forces and Motion: Basic" 

The ids for each link (only two) are 2010_exploration and 2010_guided

Let me know when you have the links ready!

**Comment by zepumph** [comment]
Here are the final links for FAMB. These are ready to be used for recording. Let me know when you want me to make the link public for the study.

Exploration:
`<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.11-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=Enter%20your%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-task-2010_exploration-0921&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">
  link to the simulation Forces and Motion: Basics</a>`

Guided:
`<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.11-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=Enter%20your%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-task-2010_guided-0921&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">`
  link to the simulation Forces and Motion: Basics</a>

**Comment by DianaTavares** [comment]
The link should be public for students from September 20 to 29.

**Comment by zepumph** [comment]
It was said in a meeting yesterday that ideally we wouldn't have the close warning because it could potentially cause students to stay on the page after the warning, but with metacog no longer recording data.

**Comment by zepumph** [comment]
New final links are below. Please use the test link for testing, otherwise extra sessions will be recorded to the official widget ids.

```
Exploration:
<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.12-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-2010_exploration-0921&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">link to the simulation Forces and Motion: Basics</a>

Guided:
<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.12-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-2010_guided-0921&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">link to the simulation Forces and Motion: Basics</a>

test:
<a href="https://phet-io.colorado.edu/sims/forces-and-motion-basics/2.1.12-phetio/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-test&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog" target="_blank">Test with this link</a>
```
