### ISSUE TITLE
Cut off clouds, mountains, and tracks

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#269]
Device
Dell and Mac laptop
OS
Win 10 and Mac OS 10.13
Browser
Firefox
Problem description
Found in https://github.com/phetsims/QA/issues/189 and issue at least appears worse in that version as opposed to master.
Under certain conditions the track under the skateboard, the clouds in the background, and the mountains in the background can have part of their image cut off.  The clouds can also disappear at the edge rather than scrolling off.  This may be due to any of these factors, or a combination.
1. Slowed Connection
2. The act of recording
3. Resizing the window

Resizing the window is what ended up causing it on master, however the problem appeared in the version here https://github.com/phetsims/QA/issues/189 without resizing.

Steps to reproduce:
1. On firefox go to the motion screen.
2. Open the dev tools.  Allow this to change the screen size.  You can also throttle speed here (had trouble throttling speed on phettest for some reason.
3. Optional - start a recording
4. Stack the two boxes and refrigerator and push until they are at max speed.

Screenshots
![gitch cloud](https://user-images.githubusercontent.com/41024075/45776941-a5fbab00-bc11-11e8-9958-1b68aa567fb5.gif)

Will add more instances when seen.

**Comment by zepumph** [comment]
We published the maintenance version without fixing this, so I think this only applied to master right now. Unassigning.

**Comment by AgustinVallejo** [comment]
I wasn't able to reproduce this on main. Closing.
