### ISSUE TITLE
Caching issue with phetio password

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#270]
**Device**
Dell Laptop
**OS**
Win 10
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/QA/issues/190
When recording on firefox outside of incognito mode the phetio password is asked for at odd stages.  Not always first after the page has been navigated to.  I have seen it pop up after the student id and even after the back arrow is used to end the recording.  Will indicate if this interferes with playback when recordings are reviewed.  Have only seen this on firefox so far.
**Steps to Reproduce**
1. On firefox use the metacog recording method listed in the above issue.  Use a normal browser
2. X out in between recordings
3. After a few recordings this issue may appear.

Screenshots
https://drive.google.com/file/d/11UHJbbxlQ7Cfe5kjEFoAlvKTh6_GvQkB/view?usp=sharing
This also shows the firefox back arrow issue.

**Comment by zepumph** [comment]
See https://github.com/phetsims/phet-io-wrappers/issues/171, closing
