### ISSUE TITLE
Dragging iPad screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#272]
**Device**
iPad Air 2
**OS**
iOS 12
**Browser**
Safari
**Problem Description**
Seen in https://github.com/phetsims/special-ops/issues/122 while testing forces-and-motion-basics 2.1.13-rc.1 phet-io.
When dragging an object, such as a box.  The screen is dragged around as well.
**Steps to reproduce**
1. Go to the sim indicated and go to the motion screen.  Use an iPad
2. Pick up and drag the box on the skate board
3. Note behavior

**Screenshots**
https://drive.google.com/file/d/1WXusRZSdZyQXtdRs7vB_HNf9QKAhwW0Z/view?usp=sharing

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this looks a lot like https://github.com/phetsims/scenery/issues/770. From that issue, I see that 2.3 got the patch. I also see that 2.1-phet-io branch had an update to its dependencies.json in that issue, but I don't see that the change made it to the forces-and-motion-basics-2.1-phetio branch in scenery.
https://github.com/phetsims/scenery/commits/forces-and-motion-basics-2.1-phetio

**Comment by jessegreenberg** [comment]
The patch *did* however make it to the forces-and-motion-basics-2.3-phetio branch in scenery in https://github.com/phetsims/scenery/commit/40b8df8a1a39de063a69a90676b68938a3df7379.

@samreid can you please help with this? I am not sure which version needs to be maintained. Or maybe both versions do?.

**Comment by samreid** [comment]
In https://github.com/phetsims/forces-and-motion-basics/issues/273 we concluded to focus on the next minor version, and new clients can use forces-and-motion-basics 2.3.7-rc.1 until that's ready.
