### ISSUE TITLE
Should we perform a manual maintenance release of Forces and Motion: Basics 2.1 branch?

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#273]
Should we perform a manual maintenance release of Forces and Motion: Basics 2.1 branch?  It had complications during the batch process and had to be omitted.

From https://github.com/phetsims/special-ops/issues/122#issuecomment-436326632.

> We can proceed with the batch deploys and redeploy forces-and-motion-basics 2.1-phetio separately. It is also unclear how important it is to redeploy forces-and-motion-basics 2.1-phetio now anyways, since clients don't automatically get the maintenance-released versions for this older branch. It seems preferable to update Forces and Motion: Basics to the latest style and give that version to clients instead. We'll discuss this with @kathy-phet and/or @ariel-phet before spending time on that step.

@zepumph @kathy-phet @ariel-phet do you recommend a manual maintenance release to address full screen on iPad for Forces and Motion: Basics 2.1 branch, or should we focus on the next minor version instead?

**Comment by ariel-phet** [comment]
Focus on the next minor version, the full screen issue is not a massively used feature from our anecdotal evidence.

**Comment by zepumph** [comment]
From this issue it seems like the bug that got MR'ed to all other sims did not get hit in this branch. There is no priority to work on this sim anytime in the future, and I believe that this sim is being used by clients out in the wild. 

From @ariel-phet's comment:
>Focus on the next minor version, the full screen issue is not a massively used feature from our anecdotal evidence.


It seems like we aren't going to go back and fix this. Closing
