### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#278]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* No needed corrections noticed
* several objects do not have visible pointer areas

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/55911108-30e7c700-5b9d-11e9-87a4-46a27b53eb0d.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/55911109-30e7c700-5b9d-11e9-9aa5-8a6baf1791d8.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/55911110-30e7c700-5b9d-11e9-9ac0-a2d8fca269df.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/55911111-30e7c700-5b9d-11e9-83f9-55463f4adc6d.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/55911112-30e7c700-5b9d-11e9-8979-53405c1b1e71.png)

**Comment by arouinfar** [comment]
https://github.com/phetsims/joist/issues/556 will discuss the possibility of automatically showing `pointerAreas` for all UI components, but according to @kathy-phet:
> I don't think its worth  spending time republishing just to make these visible though.
