### ISSUE TITLE
Use TimeControlNode for Play/Pause/Step buttons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/forces-and-motion-basics#280]
From phetsims/scenery-phet#561. A scenery-phet/TimeControlNode was created that combines the PlayPauseButton and StepForwardButton and includes PhET-iO and PDOM instrumentation. It should be used in this sim. Assigning to responsible dev.

**Comment by jessegreenberg** [comment]
The API for StepButton changed and isPlayingProperty was replaced with enabledProperty. When TimeControlNode is used in this sim the setting of enabledProperty can be removed because it is the default behavior for TimeControlNode.

**Comment by amanda-phet** [comment]
This seems like something that could be addressed with https://github.com/phetsims/forces-and-motion-basics/issues/304

**Comment by AgustinVallejo** [comment]
Addressed in the above commit. However, there is currently a slightly different behavior: When you pause the sim in the published version, the play/pause button changes scales and becomes bigger. This is not present in the TimeControlNode component and I wouldn't know how if there's currently an easy way of implementing, nor it would be consistent with other sims.

Assigning back to @amanda-phet to chime in on this and close if done

**Comment by zepumph** [comment]
This caused some PhET-iO validation trouble, but FAMB isn't active in its phet-io implementation, so let's turn off validation until we work on PhET-iO again.

**Comment by amanda-phet** [comment]
>When you pause the sim in the published version, the play/pause button changes scales and becomes bigger. This is not present in the TimeControlNode component and I wouldn't know how if there's currently an easy way of implementing, nor it would be consistent with other sims.

I think the custom resizing is unnecessary and using a common component is more important. This looks good to me.
