### ISSUE TITLE
Improve valueType for AnimationStateIO

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#282]
During https://github.com/phetsims/tandem/issues/211 I noted this TODO.  I decided to move it to this issue.  It may not need attention at the moment, but I'll assign to @zepumph since he is listed as author of the file.

```js
const AnimationStateIO = new IOType( 'AnimationStateIO', {
  valueType: Object, // TODO:  https://github.com/phetsims/tandem/issues/211, convert to a named type
  documentation: 'Data that is stored in the "Item.animationState" Property. Type to serialize the data object across the iframe'
} );
```

**Comment by zepumph** [comment]
Unassigning until phet-io work in FAMB continues.

**Comment by zepumph** [comment]
Because of https://github.com/phetsims/forces-and-motion-basics/issues/285 and the creation of ObjectLiteralIO in https://github.com/phetsims/phet-io/issues/1616, @jessegreenberg  and I were able to get rid of AnimationStateIO. I'm going to close this issue.
