### ISSUE TITLE
User request: quantized friction slider

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#284]
> It would be REALLY helpful if the friction slider was quantized, meaning we should set it on some arbitrary value and then go back to that value after resetting the app or two students could be sure they are using the same amount of friction.

**Comment by ariel-phet** [comment]
@arouinfar although I don't think it is appropriate to have this slider be "quantized" we could consider making it a more discrete slider for experiment repetition. I feel like that would be a relatively easy change. Add some tick marks, make things more snappy (might be a good change for description in the future).

**Comment by arouinfar** [comment]
Agreed @ariel-phet. For experiment repetition, I'd go with an 11-tick slider and snap the thumb to the tick marks.

![image](https://user-images.githubusercontent.com/8419308/98254810-f6d9d500-1f39-11eb-98fc-0eefbd1b023e.png)

I don't think we have any sliders where the thumb snaps in the neighborhood of a tick, but is continuous elsewhere. Either it is continuous or it is snappy. We should discuss more when this sim gets design attention again, which will probably be when this sim gets an updated PhET-iO implementation.

**Comment by amanda-phet** [comment]
Tagging this for design meeting to decide if we want to address with https://github.com/phetsims/forces-and-motion-basics/issues/304

**Comment by amanda-phet** [comment]
To meet the goals that this user request is trying to achieve, it seems like having a way to set µ (such as in preferences) is the way to do that. When we finally do a true Forces and Motion sim we should go this route. Or with PhET-iO. 

We also discussed adding tick marks (so the slider is still continuous, but has reference points) so someone a try to recreate experiments, but still allow users to finely tune how much friction they want. Adding 3 tick marks (25%, 50%, and 75%) is a simple interim way we could support the user's learning goals. The gravity force slider in MSS is similar. 

Let's also investigate using hslider to add tick marks and update the thumb.

**Comment by amanda-phet** [comment]
The applied force slider still has the old thumb. Can we update that to match as well? 

![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/d80dcd62-5339-4ffb-ba44-b0d777ea46aa)

**Comment by AgustinVallejo** [comment]
Just saw this comment. The above commit addresses this. Please review and close if done.

**Comment by amanda-phet** [comment]
All looks good, thanks.

**Comment by oliver-phet** [comment]
Let's leave this issue open until the sim is republished with the change (I'll then reply to the user and close).

**Comment by marlitas** [comment]
@oliver-phet this sim is now republished with the quantized friction slider. Deployed here: https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_all.html

**Comment by oliver-phet** [comment]
Email to user sent, closing!
