### ISSUE TITLE
User request: Add stop watch

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#288]
> I'm wondering if it's possible to add a stop watch function to the force and motion basics (motion screen).  We've been using seperate stopwatches to calculate acceleration, but this doesn't work for the online kids.  I know that the sim will do it for them on the other screen, but want them to have the practice.

Assigning to @arouinfar for evaluation.

**Comment by arouinfar** [comment]
This is an interesting suggestion. We should consider it the next time this sim is resisting. Unassinging myself for now.

**Comment by amanda-phet** [comment]
Tagging for design meeting to discuss if we want to address this with https://github.com/phetsims/forces-and-motion-basics/issues/304

**Comment by amanda-phet** [comment]
Discussed, and agreed we should add a stopwatch to the Motion and Friction screens. The checkbox can go right below the Speed checkbox. We like the icon. The stopwatch can go in the sky to the left of the panel. 

![image](https://github.com/phetsims/forces-and-motion-basics/assets/7852916/904fa312-90db-4db1-b5a2-4ceb679bdc78)

**Comment by arouinfar** [comment]
The stopwatch also looks good to me. The PhET-iO instrumentation of this sim predates Hydrogen and our modern design processes. It will be a significant effort to republish this simulation with PhET-iO, and we're only including phet-brand in the upcoming release, so I think we can defer instrumenting the Stopwatch until later.

The Stopwatch should be tested during the QA process, so assigning back to @AgustinVallejo to make sure this is on the list of issues for QA during dev testing.

**Comment by Luisav1** [comment]
As the region and culture publication won't include PhET-iO, assigning this as ready for review by QA during dev testing.

**Comment by Nancy-Salpepi** [comment]
The stopwatch has been added to the Motion and Friction Screens. 
Closing.

**Comment by oliver-phet** [comment]
@Nancy-Salpepi I don't see the stop watch in the published sim? Is this in an upcoming version (2.4.0)?

Also, please keep "user requests/suggestion" tickets open and assign to me so that I can alert the requesting user. Thanks!

**Comment by Nancy-Salpepi** [comment]
Sorry @oliver-phet! It is in dev test right now.

**Comment by marlitas** [comment]
@oliver-phet this sim has now been republished with the stopwatch added. Deployed here: https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_all.html

**Comment by oliver-phet** [comment]
Email to user sent, closing!
