### ISSUE TITLE
User request: new team colors (color customization)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/forces-and-motion-basics#289]
> I was wondering if you could possibly change the color of the figures in the Forces and Motion: Basics simulation? In my school we are constantly dealing with gangs and their influences. The two major colors of rival gangs are blue and red. It would make the conversation a lot better if it wasn't blue versus red.

ON: This request is very specific (and there's likely not any combination of colors that don't have consequences in some community), but I'm posting an issue because this seems to be another example where having additional customization options would be useful to our users.

**Comment by arouinfar** [comment]
I think we likely create a preference for the team colors and hook it up to a query parameter. Let's consider when we revisit this sim, unassigning myself for now.

**Comment by amanda-phet** [comment]
Tagging for design meeting to discuss if we want to address this with https://github.com/phetsims/forces-and-motion-basics/issues/304

**Comment by amanda-phet** [comment]
It would be relatively easy to recolor this artwork. 

We may want to rename the code references from blue/red to left/right so it is color-agnostic (and consistent with the direction of the forces). 

Considering replacing blue with purple. We will confirm that these colors pass color blindness.

**Comment by amanda-phet** [comment]
I'd like to confirm here that we should add a Simulation tab to the preferences dialog, and add an option for the Net Force pullers. Not sure what to call it, or how to style it, but I'm thinking rectangular radio buttons with images of the colors, or aqua radio buttons that say "blue/red" and "purple/orange."

**Comment by amanda-phet** [comment]
Orange and Purple pullers are uploaded! 

For the Preferences, can you add a Simulation tab with the following for the setting: 

**Net Force Puller Colors**
- Blue and Red (selected)
- Purple and Orange

Also, can you make this a query parameter, so it is selected at sim startup for the teachers who want this feature? I'm not sure what to name it... perhaps `pullerColor` and the options can be `blue` or `purple`?

**Comment by Luisav1** [comment]
I've added the the option to change the pullers color in the preferences tab like so:
![image](https://github.com/user-attachments/assets/492a2614-d80a-4772-8457-a370e9d31415)

Additionally, there is now a query parameter `pullercolor` that can be set at startup. The valid values are `blueRed` and `purpleOrange`. I found it clearer to use these names instead of just `blue` and `purple` throughout the code, but I'm open to any suggestions to improve them.

I still need to change the FlagNode that's displayed when a color wins to reflect these new colors.

**Comment by amanda-phet** [comment]
OK great! 

Can you make sure the name of the control is in bold? I assumed it was handled by common code, but it might just be that we have to manually make it bold every time we add a preference.

**Comment by Luisav1** [comment]
Yes, that was an easy fix! I changed which font from the `PreferencesDialog` it was using.

The flag node is now updated as well:
![image](https://github.com/user-attachments/assets/45daab37-c0cc-4ee4-ba69-783a2c4b45dc)
![image](https://github.com/user-attachments/assets/d3e7aa17-fdff-44f9-8f1a-f948abd81f73)

This is all now ready for your review @amanda-phet.

**Comment by amanda-phet** [comment]
This looks like it's working great. Assigning to @oliver-phet to reply to the user once this sim is published.

**Comment by oliver-phet** [comment]
Will this issue receive a comment when the update is published?

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1179, confirming that the purple/orange figures have been added. The query parameter and option in the Simulation tab of the Preferences menu are working correctly.

**Comment by marlitas** [comment]
@oliver-phet This sim has now been republished with the new team colors able to access via query parameter or in preferences. Deployed here: https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_all.html

**Comment by oliver-phet** [comment]
Email to user sent, closing!
