### ISSUE TITLE
Add in Africa/ Modest, Asia, Oceania, and Latin America character sets

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/forces-and-motion-basics#304]

**Comment by Luisav1** [comment]
The preferences model and structure for portrayals is added in and FAMB is ready for the artwork @amanda-phet.

**Comment by amanda-phet** [comment]
New USA set (in svg) is ready to try out. I gave these to @Luisav1 on slack, but will put here for posterity. If these work out, I will move ahead with exporting the other regions (which are all drawn and resized, but there will be some more steps before they are ready for export)

![usaGirlHolding](https://github.com/user-attachments/assets/b1b1c330-7df8-4209-aeac-6a48074f7776)
![usaGirlSitting](https://github.com/user-attachments/assets/ad90f6f1-8c62-4aea-b1fd-64a31ab17552)
![usaGirlStanding](https://github.com/user-attachments/assets/fc24747c-042a-4d1b-9862-8a22e7224299)
![usaManHolding](https://github.com/user-attachments/assets/c503fa43-8963-462c-a64d-494b7df6ad55)
![usaManSitting](https://github.com/user-attachments/assets/c4deeb62-38ad-4d8e-8fc8-c5a8091ad70c)
![usaManStanding](https://github.com/user-attachments/assets/4cebf34e-f6e6-4814-93e4-3c63084352bc)

**Comment by amanda-phet** [comment]
I will ask about this in the region and culture channel!

**Comment by amanda-phet** [comment]
Let's go ahead and remove Africa (Modest) from the preferences dropdown.

**Comment by samreid** [comment]
I removed Africa (modest) in the commit. @amanda-phet can you please review/test and summarize what changes remain for this issue?

**Comment by kathy-phet** [comment]
In recent client meetings, it was again found that clients using products in particular regions value the positive affirmation that a character set is "modest". So we should keep Africa (modest) setting as an option, even if at the moment it is just a duplicate of the Africa setting. 

@samreid - Can you please revert the removal of this option, Sam?

**Comment by samreid** [comment]
I reverted the removal and tested that it worked OK at runtime.

**Comment by amanda-phet** [comment]
I see both in Preferences. Closing.
