### ISSUE TITLE
Address `strictAxonDependencies: false`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#306]
For https://github.com/phetsims/axon/issues/441, @samreid added 1 occurrence of `strictAxonDependencies: false` to this sim. It should be inspected/addressed when this sim is worked on.

I believe the missing dependency is `model.accelerationProperty`, in WaterBucketNode:

```ts
    const deltaProperty = new DerivedProperty( [ model.timeProperty, item.draggingProperty ], ( time, dragging ) => {
...
      const acceleration = model.accelerationProperty.get();
...
      strictAxonDependencies: false
```

**Comment by Luisav1** [comment]
This was addressed above. Closing.
