### ISSUE TITLE
Add dynamic locale

### ISSUE THREAD

**Issue by Luisav1** [phetsims/forces-and-motion-basics#309]
All string properties are present, need to implement the necessary changes so the view updates whenever these string properties change.

**Comment by Luisav1** [comment]
@amanda-phet Dynamic locale is done and ready for a quick review!

**Comment by amanda-phet** [comment]
A few things I'm wondering about after trying out `stringTest=dynamic`

I think the green panels should be right-aligned, and in the case of a long string the panel got wider in the right direction, and I think it should get wider in the left direction. 
<img width="1102" alt="Screenshot 2024-04-30 at 8 39 34 PM" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/12152535-50fc-43e2-a2ed-df6d3ade9926">

I noticed the friction slider moved around a bit with different string lengths, and I'm not sure if that's desired or not. It seems to me that the slider should always be centered. 

Here is the original and a long string looking expected: 
<img width="229" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/fa338078-4103-4e60-a439-e48dc3755eda">

<img width="226" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/9918dbd7-c51a-433d-a1b9-82e49b7e3306">

These two sliders are wider, specifically with the right end getting closer to the edge of the panel: 
<img width="229" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/f9f2f294-90b5-47ed-a021-1735b27df31c">

<img width="227" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/5954246b-e0cc-49ef-9a4a-67e2021b3fd0">

The icons in the green panel on the 4th screen need to be right-aligned with the panel, not the strings: 
<img width="1102" alt="image" src="https://github.com/phetsims/forces-and-motion-basics/assets/7852916/ecf0cfed-e084-4853-9cd6-9a9c19f68b7b">

**Comment by amanda-phet** [comment]
This looks great to me! I'm sure QA will do another review so I think this can be closed.
