### ISSUE TITLE
Vestigial dependency on vibe?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/forces-and-motion-basics#316]
In preparation for republishing this sim...

In package.json:

```json
    "phetLibs": [
      "vibe"
    ],
```

I don't see any vibe imports in this sim. Is it possible that it was converted to tambo, and this dependency is vestigial?

**Comment by samreid** [comment]
There is an import here:

https://github.com/phetsims/forces-and-motion-basics/blob/1a5190037b957222687515670f9e0b7424e94958/js/netforce/view/NetForceScreenView.js#L14

That being said, tambo would be better.

**Comment by samreid** [comment]
In switching away from vibe and toward tambo, the simulation picks up standard UI sounds. In testing, it sounded OK to me. @amanda-phet how does it sound to you?

**Comment by arouinfar** [comment]
> I generally don't like UI sounds when there are "silent" interactions, especially the most important pedagogical interactions.

I agree with @amanda-phet. At minimum, we would need to add the common code grab/release sound for all draggable objects. The click interval for the Applied Force slider needs adjustment, too. Even then, the sim could still potentially sound empty. 

> @Nancy-Salpepi also noticed that the Net Force screen has a sound button for the cheering sound. Should we remove this now that we have a global sound control?

I think so. Having two sound buttons with the same iconography is confusing and bad UX. We don't typically allow users to turn off one particular sound unless it's persistent like the sound waves in Fourier or Waves Intro.

**Comment by pixelzoom** [comment]
Unassigning myself, since I'm not involved with this sim.   My only role here was to report the undesirable dependency on vibe.

**Comment by samreid** [comment]
Thanks for the discussion. It seems this issue "remove depedency on vibe" is complete, and I'll close this issue. I'll open a new issue about sonification.

**Comment by marlitas** [comment]
I discovered that vibe was still being referenced in `tsconfig.json` during an RC build. I went ahead and removed that and now need to cherry-pick.

**Comment by marlitas** [comment]
Cherry picked above. This can be closed again.
