### ISSUE TITLE
Update sonification

### ISSUE THREAD

**Issue by samreid** [phetsims/forces-and-motion-basics#320]
When the dependency on vibe was removed in https://github.com/phetsims/forces-and-motion-basics/issues/316, the simulation picked up sound effects for checkboxes, buttons, and sliders.

@amanda-phet said:

> I generally don't like UI sounds when there are "silent" interactions, especially the most important pedagogical interactions. In other sims, we've used a generic grab/release sound for interactive components that don't have a default UI sound. I haven't gone through each screen yet, but that's what I would recommend adding to this sim.
> 
> @Nancy-Salpepi also noticed that the Net Force screen has a sound button for the cheering sound. Should we remove this now that we have a global sound control?

@arouinfar commented:

> > I generally don't like UI sounds when there are "silent" interactions, especially the most important pedagogical interactions.
> 
> I agree with @amanda-phet. At minimum, we would need to add the common code grab/release sound for all draggable objects. The click interval for the Applied Force slider needs adjustment, too. Even then, the sim could still potentially sound empty. 
> 
> > @Nancy-Salpepi also noticed that the Net Force screen has a sound button for the cheering sound. Should we remove this now that we have a global sound control?
> 
> I think so. Having two sound buttons with the same iconography is confusing and bad UX. We don't typically allow users to turn off one particular sound unless it's persistent like the sound waves in Fourier or Waves Intro.

So for this issue, I think we would need to:
- [x] Add grab/drop sounds for the objects on the net force screens
- [x] Add grab/drop sounds for the objects on the motion screens
- [x] Improve the click interval for the Applied Force and/or other sliders
- [x] Remove the "sound" button within the in the Net Force screen.

There is also a proposal for a clickety-clack sound to indicate the speed the skateboard goes over the sidewalk cracks in #151.

@amanda-phet should this design + implementation work be done the current Region & Culture release?

**Comment by arouinfar** [comment]
> Remove the "sound" button within the in the Net Force screen.

Even if we decide not to add UI sounds, shouldn't we still do this? I could be missing some nuance, but I thought the changes in https://github.com/phetsims/forces-and-motion-basics/issues/316 meant that we were using tambo for the cheering sound, so the audio toggle button is in the navbar. This is similar to sims with game sounds, but no other UI sounds, such as Balancing Act.

**Comment by amanda-phet** [comment]
Since @marlitas is going to work on this, I'll assign to her! 

We discussed and decided that sonification (#151 ) is beyond the scope of this sim release.

**Comment by amanda-phet** [comment]
Everything is sounding good to me! I'll leave this open for QA to confirm everything has a sound, but I think it's good to go.

**Comment by Nancy-Salpepi** [comment]
Everything has a sound and the clapping sound is working well on the Net Force screen. 
I do see one problem where something has a grab sound when it shouldn't. I will make a separate issue for that and close this one.
