### ISSUE TITLE
Stopwatch still present and running on Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/forces-and-motion-basics#321]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/orgs/phetsims/projects/91/views/1?pane=issue&itemId=88747971&issue=phetsims%7Cqa%7C1179 and related to https://github.com/phetsims/forces-and-motion-basics/issues/288, on the Motion and Friction screens the Stopwatch checkbox stays checked and the stopwatch keeps running after pressing Reset All. 

A second issue I see is that the stopwatch is still running when I uncheck and then recheck the checkbox. 

**Steps to reproduce**
1. On the Motion or Friction screen, check the Stopwatch checkbox
2. Press Play button on the stopwatch
3. Press Reset All
4. Uncheck and then recheck the checkbox

**Visuals**

https://github.com/user-attachments/assets/b8bb450c-c378-48db-be88-58eead171c8f

**Comment by KatieWoe** [comment]
Related, unchecking the stopwatch box does not stop and reset the stopwatch. It does in other sims, such as Kepler's Law.
![uncheckwatch](https://github.com/user-attachments/assets/3e20e8f2-4a45-41a0-bc88-1c5e4baa97ba)

**Comment by Nancy-Salpepi** [comment]
Thanks for commenting @KatieWoe! I mentioned this as well in my original comment, but I can see how it would have been missed.

**Comment by marlitas** [comment]
This is addressed by the above commit. Over to @Nancy-Salpepi or @KatieWoe to confirm it is fixed on main.
