### ISSUE TITLE
Large time goes off the edge of the stopwatch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#323]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1179
If the stop watch records for over 100 minutes, the time will go off the edge of the stopwatch. Reproducing this takes less time if you use `?speed=10`.

**Visuals**
![longnumberswatch](https://github.com/user-attachments/assets/2819edf6-551e-47b8-a694-80ae2e2bf3bb)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Forces and Motion: Basics‬
URL: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-dev.7/phet/forces-and-motion-basics_all_phet.html?speed=10
Version: 2.4.0-dev.7 2024-11-26 17:47:57 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/forces-and-motion-basics/issues/288

**Comment by arouinfar** [comment]
If I'm not mistaken, StopwatchNode should have an option for a max time. In this context 59:59.99 seems appropriate. There is no need for the stopwatch to run longer than 1 hour.

**Comment by marlitas** [comment]
I set the max range as requested above and this should now be addressed on main. Over to @KatieWoe to review and close if all looks well.

**Comment by KatieWoe** [comment]
Looks good on main
