### ISSUE TITLE
Sum of forces text bounces

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#325]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1179
On the third and forth screen, if you have the Sum of Forces box checked, the text bounces up and down as the force arrow under it changes. This does not seem to happen in the published sim.

**Visuals**
![bouncingtext](https://github.com/user-attachments/assets/89f2bca2-02f5-40cc-90c8-5d1aa74021d2)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Forces and Motion: Basics‬
URL: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-dev.7/phet/forces-and-motion-basics_all_phet.html
Version: 2.4.0-dev.7 2024-11-26 17:47:57 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Addressed above. Over to @KatieWoe to review and close if all looks well.
