### ISSUE TITLE
Yellow highlights for knots are missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/forces-and-motion-basics#329]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1179, on the Net Force screen, there is a yellow highlight that appears for the knots in the published version that is missing in the dev version. 

**Visuals**
<img width="385" alt="Screenshot 2024-11-29 at 9 19 06 AM" src="https://github.com/user-attachments/assets/92afbd13-b9ca-4f97-a4c5-8bcada22c4fd">.  <img width="385" alt="Screenshot 2024-11-29 at 9 19 21 AM" src="https://github.com/user-attachments/assets/53ef4626-ab99-4429-997f-695dfa034249">

**Comment by marlitas** [comment]
This looks like it was taken out as a part of https://github.com/phetsims/forces-and-motion-basics/issues/275. I'm assuming that means it does not need to be added back in and would theoretically be replaced by interactive highlights once alt-input is enabled in this sim. However, I would like to confirm that this is no longer a feature for this sim. 

@amanda-phet or @arouinfar can you confirm the design choice and close if no further work needs to be done?

**Comment by arouinfar** [comment]
The yellow highlights were present in the [1.0.0](https://phet-dev.colorado.edu/html/forces-and-motion-basics/1.0.0/forces-and-motion-basics_en.html) version published in 2013 and the original Java version, and predates inclusive design at PhET. Removing the highlight in #275 seems like a mistake.

This feature highlights the knot a puller will snap to when released. It is different from an interactive highlight which displays the pointer focus.

Imo, this is a regression that should be addressed before publication.

**Comment by marlitas** [comment]
I brought the knot highlights back in the above commits. Since this is code that has been brought back from 2019 I would like to keep this issue open for QA to thoroughly verify in the upcoming RC.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2
Closing.
