### ISSUE TITLE
Text overlaps after switching between some locales

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/forces-and-motion-basics#332]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1179, with some locales the text can overlap after switching between them. 

**Steps to reproduce**
Here is an example:
1. On the Friction screen, have the first 3 checkboxes checked. 
2. Move Friction slider all the way to the right
3. Press Pause
4. Change locale to
                   <img width="58" alt="Screenshot 2024-11-29 at 2 23 36 PM" src="https://github.com/user-attachments/assets/a876273b-7490-4e84-b8d0-ec9f86bb17d3">
5. Move the applied force slider to ~300N
6. Change locale to Greek

Once you change the applied force, the text will "fix" itself. 

**Visuals**
<img width="959" alt="Screenshot 2024-11-29 at 2 20 59 PM" src="https://github.com/user-attachments/assets/08c553fc-f2a2-4717-b5d7-737f64729a8d">

**Comment by marlitas** [comment]
This should be addressed in the above commit. Over to @Nancy-Salpepi to confirm on main and close it all looks good!

**Comment by Nancy-Salpepi** [comment]
This good on main. Closing!
