### ISSUE TITLE
Drag of figure and slider may not be interupted by reset all

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#335]
**Device**
iPad 10th gen
**OS**
iPadOS 18.1.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/1179
If you are dragging the mannequin or friction slider on the 2nd, 3rd, or 4th screen and hit reset all you will still be dragging that object.
**Visuals**

https://github.com/user-attachments/assets/2691d636-e3af-4535-b9b1-6792d12ed864

**Comment by marlitas** [comment]
This should be fixed in the above commit. Over to @KatieWoe to confirm and close if all looks well.

**Comment by KatieWoe** [comment]
Looks good in main
