### ISSUE TITLE
Track/Road doesnt appear in Firefox

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/forces-and-motion-basics#337]
**Test device**
Win 11 23H2

**Operating System**
Win 11 23H2

**Browser**
Firefox 133.0

**Problem description**
from https://github.com/phetsims/qa/issues/1184 Track/Ground doesn't appear at all or correctly on Firefox. This happens in both RC 2 and published. Causes a bit of a funny optical illusion that makes it seem like the man is sliding. This Bug doesn't appear in my versions of Chrome either.

**Steps to reproduce**
Open up the sim in either a private tab or a regular tab and navigate to Motion/Friction/Acceleration 

**Visuals**
![image](https://github.com/user-attachments/assets/b63ef2fb-acb9-4c85-80ee-60acd7c699a3)
![image](https://github.com/user-attachments/assets/c4160e36-cd11-4002-be1d-2b5daba21c87)
![image](https://github.com/user-attachments/assets/4926fbf5-0a04-4b63-9d9a-14f8c2113f5d)

https://github.com/user-attachments/assets/995d16d1-de77-4ad7-acbb-a67a1752ae37

<details>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Forces and Motion: Basics‬
URL: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-rc.2/phet/forces-and-motion-basics_all_phet.html
Version: 2.4.0-rc.2 2024-12-05 00:58:08 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
Language: en-US
Window: 2048x1019
Pixel Ratio: 1.25/1
WebGL: disabled (WebGL creation failed: * tryANGLE (FEATURE_FAILURE_EGL_NO_CONFIG) * Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS) WebGL creation failed: * tryANGLE (FEATURE_FAILURE_EGL_NO_CONFIG) * Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS) )
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Very odd. I don't see it on my device. Other things seem to be missing in those screenshots, such as the stopwatch

**Comment by Matthew-Moore240** [comment]
> Very odd. I don't see it on my device. Other things seem to be missing in those screenshots, such as the stopwatch

Yup, just confirmed on a different system using Firefox that the sim shows up totally normal.

**Comment by Matthew-Moore240** [comment]
I cleared the cache and restarted the PC and now the sim is looking and working as intended, Apologies!

<details>
<summary>Pictures</summary>

![image](https://github.com/user-attachments/assets/229491f0-acd2-4eb3-8a0b-33eed85a2880)
![image](https://github.com/user-attachments/assets/d94df53e-8090-47d4-b287-ddf54d44bb4a)
![image](https://github.com/user-attachments/assets/14dcf3f0-203c-43cf-a24c-6373f5d144d2)

**Comment by marlitas** [comment]
It sounds like we can close this issue then? Please reopen if I am incorrect.
