### ISSUE TITLE
Firefox 24 OS X 10.6.8 performance is abysmal

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/forces-and-motion-basics#63]
Testing 1.0.0-rc.29 on the Big Mac

**Comment by samreid** [comment]
Things are speedy on my MacBook Air 2012 running Firefox 38.0.5 on OS X 10.10.2.  @ariel-phet do you want to assign specific testing for this issue on other platforms, or just wait for things to come up in a formal QA cycle?

**Comment by ariel-phet** [comment]
I am going to go ahead and close this issue since we will be redeploying the sim and many updates have been made.
