### ISSUE TITLE
Graphics quality low in Firefox on Mac OSX 

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/forces-and-motion-basics#86]
Test device: Macbook Pro (Retina, Mid-2012)

Operating System: Mac OSX 10.9

Browser: Firefox 25.0.1

Problem description: Poor graphics quality -- Lines on some graphics appear choppy and jagged when rendered in Firefox.

This is especially obvious for the man and girl in Motion, Friction, or Acceleration; also noticeable with the garbage can and water bucket.

On the same device, lines appear smooth and well-resolved in other browsers, e.g. Chrome, Safari.

Steps to reproduce: Noticeable when any of these tabs are open. Also reproducible in Firefox on an older, non-Retina display Macbook Pro (OSX 10.7.5).

Severity: ?

Screenshots For Comparison:
FIREFOX
![screen shot 2013-11-22 at 1 14 58 pm](https://f.cloud.github.com/assets/4682895/1603988/7e9f39ac-53b4-11e3-8296-3dc00122e59b.png)

CHROME
![screen shot 2013-11-22 at 1 17 03 pm](https://f.cloud.github.com/assets/4682895/1603990/93bc1008-53b4-11e3-8160-958adb92f667.png)

Troubleshooting information (do not edit):

Name: Forces and Motion: Basics

URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.0.0-rc.50/forces-and-motion-basics_en.html

Version: 1.0.0-rc.50

Features missing: flexbox, touch

Flags: pixelRatioScaling

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:25.0) Gecko/20100101 Firefox/25.0

Language: en-US

Window: 1024x544

Pixel Ratio: 2/1

WebGL: WebGL 1.0

GLSL: WebGL GLSL ES 1.0

Vendor: Mozilla (Mozilla)

Vertex: attribs: 16 varying: 16 uniform: 1024

Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)

Max viewport: 16384x16384

OES_texture_float: true

**Comment by samreid** [comment]
Perhaps a great opportunity to use mipmap!?  (Exclamation point used to refer to plugin syntax, not incredulity).

**Comment by samreid** [comment]
Mipmap doesn't seem to help much.  I tested mipmap like so:

```js
  var girlStandingImage = require( 'mipmap!FORCES_AND_MOTION_BASICS/girl-standing.png' );
  var manStandingImage = require( 'image!FORCES_AND_MOTION_BASICS/girl-standing.png' );
```

so the image on the left is mipmap with default settings, image on the right is normal image.  On Chrome, I see:

![image](https://cloud.githubusercontent.com/assets/679486/8192551/2dea2640-142c-11e5-8ccb-a58ea82e43fa.png)

On Firefox I see:

![image](https://cloud.githubusercontent.com/assets/679486/8192563/3d7025e2-142c-11e5-8489-32969d51cc7b.png)

So it appears that (a) I am misunderstanding something about mipmaps or (b) Firefox still has suboptimal rendering even for our mipmaps.  Can @jonathanolson take a look and let me know if this is what you expected?

**Comment by jessegreenberg** [comment]
Assigning to myself to verify that this is still an issue.

**Comment by jessegreenberg** [comment]
No noticeable difference between Windows 10 Firefox and Chrome.  ItemNodes in master are represented with the image plugin.

**Comment by jessegreenberg** [comment]
Will verify on an OSX device tomorrow.

**Comment by samreid** [comment]
Here's a full screen screenshot from iPad Air 11" running the built version of master, if that helps!

![image](https://cloud.githubusercontent.com/assets/679486/13306679/119a6270-db23-11e5-896a-449e84426640.png)

**Comment by jessegreenberg** [comment]
Yes it does, thanks @samreid!  New pusher looks pretty good, but standing phet-girl and phet-man images look pretty pixelated.

**Comment by jessegreenberg** [comment]
Provided assets of the standing girl and man image are pretty large, we can try the original assets with a mipmap scaling level or 1 or 2.

**Comment by jessegreenberg** [comment]
Recently tried to export pre-scaled images from AI, but there was a reduction in quality from the scaling in illustrator that is now visible in all browsers.  I will try to export with some other settings to see if I can get sharp images exported at the dimension we need.

If that doesn't help, I will try to scale *up* the images in illustrator do a dimension where we can use a first level mipmap.

**Comment by samreid** [comment]
> Recently tried to export pre-scaled images from AI, but there was a reduction in quality from the scaling in illustrator that is now visible in all browsers.

Please try File=>"Save for Web"  The File=>Export option doesn't seem to have any scaling options.

**Comment by jessegreenberg** [comment]
Yes, "Save for Web" is what I tried initially.  I was hoping something like 

"Object"=>"Transform"=>"Scale"  then "Export" .png with resolution and anti-aliasing options would help export higher quality images.

**Comment by jessegreenberg** [comment]
@samreid briefly collaborated with me on this.  We played with a few image scaling options and determined that in Firefox, most images looked fuzzy after being scaled in Joist.

We determined that using mipmaps for these images was the best way to go and offered the best clarity of image for OSX + Safari.

**Comment by jessegreenberg** [comment]
In commit above, we are using mipmap plugin for the images instead of the image plugin.  Resolution is slightly better on OSX Firefox, but still not as crisp as other browsers.

**Comment by jessegreenberg** [comment]
RC for 2.0.0 has been published, and the image quality is improved so I am going to remove the S2015R tag.  But I don't feel like this issue should be closed yet because the image quality in iOS Firefox is still not as good as other platforms.

**Comment by jessegreenberg** [comment]
Removing assignment and adding deferred label since we are not looking at this for the next 2.1 minor release.

**Comment by samreid** [comment]
Here's a built version running on mac firefox: 
![image](https://user-images.githubusercontent.com/679486/66256939-76eaa580-e750-11e9-9086-114a784c7878.png)

This seems good and comparable to the quality on our other sims, closing.
