### ISSUE TITLE
Left side small figurines in "Tug of War" jump back in location on the rope when clicked.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/forces-and-motion-basics#88]
Test device: MacBook Pro
Operating System: 10.7
Browser: Google Chrome
Problem description:
In the "Tug of War" screen of the sim; the small blue left hand side figurines jump back in location on the rope when clicked.

Steps to reproduce:
Open the sim
Select "Tug of War"
Drag one of the smallest blue figurines to the section of the rope closest to the cart
Click on the figurines hands

The figurine will move back one position with out any adjustment with the mouse.

Severity:
Not extremely sever, but should be fixed.

Screenshots:
![forces-motion-basics1 0 0-rc 51tugofwarbug](https://f.cloud.github.com/assets/5631059/1676197/50600386-5d15-11e3-8866-faf67aef3264.png)

Troubleshooting information (do not edit):
Name: Forces and Motion: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/1.0.0-rc.51/forces-and-motion-basics_en.html
Version: 1.0.0-rc.51
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
Language: en-US
Window: 1280x705
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by samreid** [comment]
I moved @bryo5363's last comment to a new issue and will close this one based on the verification above.
