### ISSUE TITLE
Objects spawn before background

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/forces-and-motion-basics#96]
Test device: ASUS 
Operating System: win 8 64-bit
Browser: FF 31.0
Problem description:
When changing between screens objects spawn before background spawns.

Severity: High. This is a published sim on our html page.
Screenshots:
![espb](https://cloud.githubusercontent.com/assets/5631059/4004650/9331a9f8-2984-11e4-860e-3fada7ace71f.png)

Troubleshooting information (do not edit):

Name: Forces and Motion: Basics

URL: http://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html

Version: 1.0.0

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0

Language: en-US

Window: 1366x657

Pixel Ratio: 1/1

WebGL: WebGL 1.0

GLSL: WebGL GLSL ES 1.0

Vendor: Mozilla (Mozilla)

Vertex: attribs: 16 varying: 10 uniform: 254

Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)

Max viewport: 8192x8192

OES_texture_float: true

**Comment by samreid** [comment]
It seems difficult to reproduce this problem, we can reopen if it appears again during QA testing.
